// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#ifndef __BINDINGS_SWIFT_SPIKE_H
#define __BINDINGS_SWIFT_SPIKE_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct swift_spike_string_t {
  uint8_t*ptr;
  size_t len;
} swift_spike_string_t;

// Imported Functions from `wandr:swift-spike/host`
extern void wandr_swift_spike_host_log(swift_spike_string_t *msg);
// stand-in for a wasi:canvas draw; argb = 0xAARRGGBB
extern void wandr_swift_spike_host_draw_rect(float x, float y, float w, float h, uint32_t argb);

// Exported Functions from `swift-spike`
void exports_swift_spike_run(void);

// Helper Functions

// Sets the string `ret` to reference the input string `s` without copying it
void swift_spike_string_set(swift_spike_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void swift_spike_string_dup(swift_spike_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void swift_spike_string_dup_n(swift_spike_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void swift_spike_string_free(swift_spike_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
