// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!

@file:OptIn(kotlin.wasm.unsafe.UnsafeWasmMemoryApi::class, kotlin.wasm.ExperimentalWasmInterop::class, kotlin.wasm.unsafe.ComponentModelInternalApi::class)

package bindings

import impl.*

import bindings.runtime.*


@kotlin.wasm.WasmImport("wasi:canvas/types@0.0.1", "[resource-drop]shader")
internal external fun __cm_resource_abi_import_Types_Shader_drop(handle: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/types@0.0.1", "[resource-drop]image")
internal external fun __cm_resource_abi_import_Types_Image_drop(handle: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/types@0.0.1", "[method]image.width")
internal external fun __wasm_import_width(p0: kotlin.Int): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/types@0.0.1", "[method]image.height")
internal external fun __wasm_import_height(p0: kotlin.Int): kotlin.Int



@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[resource-drop]picture")
internal external fun __cm_resource_abi_import_Draw_Picture_drop(handle: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[resource-drop]graphics")
internal external fun __cm_resource_abi_import_Draw_Graphics_drop(handle: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]graphics.linear-gradient")
internal external fun __wasm_import_linearGradient(p0: kotlin.Int, p1: kotlin.Float, p2: kotlin.Float, p3: kotlin.Float, p4: kotlin.Float, p5: kotlin.Int, p6: kotlin.Int, p7: kotlin.Int): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]graphics.radial-gradient")
internal external fun __wasm_import_radialGradient(p0: kotlin.Int, p1: kotlin.Float, p2: kotlin.Float, p3: kotlin.Float, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Int): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]graphics.sweep-gradient")
internal external fun __wasm_import_sweepGradient(p0: kotlin.Int, p1: kotlin.Float, p2: kotlin.Float, p3: kotlin.Float, p4: kotlin.Float, p5: kotlin.Int, p6: kotlin.Int, p7: kotlin.Int): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]graphics.shader-blend")
internal external fun __wasm_import_shaderBlend(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]graphics.image-pattern")
internal external fun __wasm_import_imagePattern(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Float, p7: kotlin.Float, p8: kotlin.Float, p9: kotlin.Float, p10: kotlin.Float, p11: kotlin.Float, p12: kotlin.Float, p13: kotlin.Float, p14: kotlin.Float): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]graphics.decode-image")
internal external fun __wasm_import_decodeImage(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]graphics.image-from-rgba8")
internal external fun __wasm_import_imageFromRgba8(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]graphics.new-offscreen")
internal external fun __wasm_import_newOffscreen(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]graphics.start-recording")
internal external fun __wasm_import_startRecording(p0: kotlin.Int, p1: kotlin.Float, p2: kotlin.Float, p3: kotlin.Float, p4: kotlin.Float): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[resource-drop]canvas")
internal external fun __cm_resource_abi_import_Draw_Canvas_drop(handle: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.width")
internal external fun __wasm_import_width0(p0: kotlin.Int): kotlin.Float

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.height")
internal external fun __wasm_import_height1(p0: kotlin.Int): kotlin.Float

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.save")
internal external fun __wasm_import_save(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.save-layer")
internal external fun __wasm_import_saveLayer(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Float, p3: kotlin.Float, p4: kotlin.Float, p5: kotlin.Float, p6: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.restore")
internal external fun __wasm_import_restore(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.translate")
internal external fun __wasm_import_translate(p0: kotlin.Int, p1: kotlin.Float, p2: kotlin.Float): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.scale")
internal external fun __wasm_import_scale(p0: kotlin.Int, p1: kotlin.Float, p2: kotlin.Float): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.rotate")
internal external fun __wasm_import_rotate(p0: kotlin.Int, p1: kotlin.Float): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.concat")
internal external fun __wasm_import_concat(p0: kotlin.Int, p1: kotlin.Float, p2: kotlin.Float, p3: kotlin.Float, p4: kotlin.Float, p5: kotlin.Float, p6: kotlin.Float, p7: kotlin.Float, p8: kotlin.Float, p9: kotlin.Float): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.clip-rect")
internal external fun __wasm_import_clipRect(p0: kotlin.Int, p1: kotlin.Float, p2: kotlin.Float, p3: kotlin.Float, p4: kotlin.Float, p5: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.clip-rounded-rect")
internal external fun __wasm_import_clipRoundedRect(p0: kotlin.Int, p1: kotlin.Float, p2: kotlin.Float, p3: kotlin.Float, p4: kotlin.Float, p5: kotlin.Float, p6: kotlin.Float, p7: kotlin.Float, p8: kotlin.Float, p9: kotlin.Float, p10: kotlin.Float, p11: kotlin.Float, p12: kotlin.Float, p13: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.clip-path")
internal external fun __wasm_import_clipPath(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.clear")
internal external fun __wasm_import_clear(p0: kotlin.Int, p1: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.draw-paint")
internal external fun __wasm_import_drawPaint(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Int, p7: kotlin.Int, p8: kotlin.Float, p9: kotlin.Int, p10: kotlin.Int, p11: kotlin.Float, p12: kotlin.Int, p13: kotlin.Int, p14: kotlin.Float): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.draw-rect")
internal external fun __wasm_import_drawRect(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.draw-rounded-rect")
internal external fun __wasm_import_drawRoundedRect(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.draw-double-rounded-rect")
internal external fun __wasm_import_drawDoubleRoundedRect(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.draw-oval")
internal external fun __wasm_import_drawOval(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.draw-line")
internal external fun __wasm_import_drawLine(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.draw-arc")
internal external fun __wasm_import_drawArc(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.draw-path")
internal external fun __wasm_import_drawPath(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.draw-image")
internal external fun __wasm_import_drawImage(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.draw-image-rect")
internal external fun __wasm_import_drawImageRect(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.draw-picture")
internal external fun __wasm_import_drawPicture(p0: kotlin.Int, p1: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[method]canvas.snapshot")
internal external fun __wasm_import_snapshot(p0: kotlin.Int, p1: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/draw@0.0.1", "[static]canvas.finish-recording")
internal external fun __wasm_import_finishRecording(p0: kotlin.Int): kotlin.Int



@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[resource-drop]paragraph")
internal external fun __cm_resource_abi_import_Layout_Paragraph_drop(handle: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph.layout")
internal external fun __wasm_import_layout(p0: kotlin.Int, p1: kotlin.Float): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph.paint")
internal external fun __wasm_import_paint(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Float, p3: kotlin.Float): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph.height")
internal external fun __wasm_import_height2(p0: kotlin.Int): kotlin.Float

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph.max-intrinsic-width")
internal external fun __wasm_import_maxIntrinsicWidth(p0: kotlin.Int): kotlin.Float

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph.min-intrinsic-width")
internal external fun __wasm_import_minIntrinsicWidth(p0: kotlin.Int): kotlin.Float

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph.alphabetic-baseline")
internal external fun __wasm_import_alphabeticBaseline(p0: kotlin.Int): kotlin.Float

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph.lines")
internal external fun __wasm_import_lines(p0: kotlin.Int, p1: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph.rects-for-range")
internal external fun __wasm_import_rectsForRange(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph.offset-at")
internal external fun __wasm_import_offsetAt(p0: kotlin.Int, p1: kotlin.Float, p2: kotlin.Float): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph.word-boundary")
internal external fun __wasm_import_wordBoundary(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[resource-drop]paragraph-builder")
internal external fun __cm_resource_abi_import_Layout_ParagraphBuilder_drop(handle: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph-builder.push-style")
internal external fun __wasm_import_pushStyle(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Float, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Int, p7: kotlin.Float, p8: kotlin.Float): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph-builder.pop-style")
internal external fun __wasm_import_popStyle(p0: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[method]paragraph-builder.add-text")
internal external fun __wasm_import_addText(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[static]paragraph-builder.new")
internal external fun __wasm_import_new(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Float, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Float, p7: kotlin.Float, p8: kotlin.Int): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/layout@0.0.1", "[static]paragraph-builder.build")
internal external fun __wasm_import_build(p0: kotlin.Int): kotlin.Int



@kotlin.wasm.WasmImport("wasi:canvas/embedding@0.0.1", "get-context")
internal external fun __wasm_import_getContext(): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/embedding@0.0.1", "[resource-drop]canvas-context")
internal external fun __cm_resource_abi_import_Embedding_CanvasContext_drop(handle: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("wasi:canvas/embedding@0.0.1", "[method]canvas-context.graphics")
internal external fun __wasm_import_graphics(p0: kotlin.Int): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/embedding@0.0.1", "[method]canvas-context.get-current-buffer")
internal external fun __wasm_import_getCurrentBuffer(p0: kotlin.Int): kotlin.Int

@kotlin.wasm.WasmImport("wasi:canvas/embedding@0.0.1", "[method]canvas-context.present")
internal external fun __wasm_import_present(p0: kotlin.Int): kotlin.Unit



@kotlin.wasm.WasmExport("my:skiko-gfx/renderer@0.1.0#render-frame")
fun __wasm_export_renderFrame(p0: kotlin.Long): kotlin.Unit {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  RendererImpl.renderFrame(p0.toULong())

}
}

@kotlin.wasm.WasmExport("my:skiko-gfx/renderer@0.1.0#on-pointer-event")
fun __wasm_export_onPointerEvent(p0: kotlin.Int, p1: kotlin.Float, p2: kotlin.Float): kotlin.Unit {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  RendererImpl.onPointerEvent(bindings.Renderer.PointerKind.values()[p0], p1, p2)

}
}

@kotlin.wasm.WasmExport("my:skiko-gfx/renderer@0.1.0#on-key-event")
fun __wasm_export_onKeyEvent(p0: kotlin.Int, p1: kotlin.Int): kotlin.Unit {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  RendererImpl.onKeyEvent(bindings.Renderer.KeyKind.values()[p0], p1.toUInt())

}
}

@kotlin.wasm.WasmExport("my:skiko-gfx/renderer@0.1.0#on-resize")
fun __wasm_export_onResize(p0: kotlin.Int, p1: kotlin.Int): kotlin.Unit {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  RendererImpl.onResize(p0.toUInt(), p1.toUInt())

}
}

@kotlin.wasm.WasmExport("my:skiko-gfx/renderer@0.1.0#on-scheduled-callback")
fun __wasm_export_onScheduledCallback(p0: kotlin.Int): kotlin.Unit {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  RendererImpl.onScheduledCallback(p0.toUInt())

}
}

@kotlin.wasm.WasmExport("my:skiko-gfx/renderer@0.1.0#on-pointer-event-v2")
fun __wasm_export_onPointerEventV2(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Float, p3: kotlin.Float, p4: kotlin.Float): kotlin.Unit {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  RendererImpl.onPointerEventV2(p0.toUInt(), bindings.Renderer.PointerKind.values()[p1], p2, p3, p4)

}
}

@kotlin.wasm.WasmExport("my:skiko-gfx/renderer@0.1.0#on-key-event-v2")
fun __wasm_export_onKeyEventV2(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int): kotlin.Unit {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  RendererImpl.onKeyEventV2(bindings.Renderer.KeyKind.values()[p0], p1.toUInt(), p2.toUInt())

}
}

@kotlin.wasm.WasmExport("my:skiko-gfx/renderer@0.1.0#on-lifecycle-changed")
fun __wasm_export_onLifecycleChanged(p0: kotlin.Int): kotlin.Unit {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  RendererImpl.onLifecycleChanged(p0.toUInt())

}
}


