// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!

@file:OptIn(kotlin.wasm.unsafe.UnsafeWasmMemoryApi::class, kotlin.wasm.ExperimentalWasmInterop::class, kotlin.wasm.unsafe.ComponentModelInternalApi::class)

package bindings

import impl.*

import bindings.runtime.*

@WitInterface("wasi:canvas/types@0.0.2")
/*external */interface Types {
  @WitImport
  companion object Import : bindings.Types {
    // <editor-fold defaultstate="collapsed" desc="Generated Import Code">
    // </editor-fold>
  }
  // START OF TYPES


  /**
  CSS/Porter-Duff blend modes (https://www.w3.org/TR/compositing-1/).
  */
  enum class BlendMode {
    SRC_OVER,
    SRC,
    DST,
    DST_OVER,
    SRC_IN,
    DST_IN,
    SRC_OUT,
    DST_OUT,
    SRC_ATOP,
    DST_ATOP,
    XOR,
    PLUS,
    MODULATE,
    MULTIPLY,
    SCREEN,
    OVERLAY,
    DARKEN,
    LIGHTEN,
    COLOR_DODGE,
    COLOR_BURN,
    HARD_LIGHT,
    SOFT_LIGHT,
    DIFFERENCE,
    EXCLUSION,
    CLEAR,
    HUE,
    SATURATION,
    COLOR,
    LUMINOSITY,
  }

  enum class PaintStyle {
    FILL,
    STROKE,
    FILL_AND_STROKE,
  }

  enum class StrokeCap {
    BUTT,
    ROUND,
    SQUARE,
  }

  enum class StrokeJoin {
    MITER,
    ROUND,
    BEVEL,
  }

  enum class FillRule {
    NONZERO,
    EVENODD,
  }

  enum class TileMode {
    CLAMP,
    REPEAT,
    MIRROR,
    DECAL,
  }

  /**
  Gaussian blur applied to the drawn geometry's mask (box shadows,
  glows). `sigma` is the Gaussian standard deviation in canvas units.
  */
  enum class BlurStyle {
    NORMAL,
    SOLID,
    OUTER,
    INNER,
  }

  class MaskBlur(
    var style: bindings.Types.BlurStyle,
    var sigma: kotlin.Float,
  )

  class Point(
    var x: kotlin.Float,
    var y: kotlin.Float,
  )

  class Rect(
    var x: kotlin.Float,
    var y: kotlin.Float,
    var width: kotlin.Float,
    var height: kotlin.Float,
  )

  /**
  Per-corner elliptical radii (order: top-left, top-right,
  bottom-right, bottom-left — CSS border-radius order).
  */
  class RoundedRect(
    var rect: bindings.Types.Rect,
    var topLeft: bindings.Types.Point,
    var topRight: bindings.Types.Point,
    var bottomRight: bindings.Types.Point,
    var bottomLeft: bindings.Types.Point,
  )

  /**
  Row-major 3x3 matrix (affine + perspective row).
  */
  class Transform(
    var m00: kotlin.Float,
    var m01: kotlin.Float,
    var m02: kotlin.Float,
    var m10: kotlin.Float,
    var m11: kotlin.Float,
    var m12: kotlin.Float,
    var m20: kotlin.Float,
    var m21: kotlin.Float,
    var m22: kotlin.Float,
  )

  /**
  Image sampling for scaled draws and image shaders.
  */
  enum class FilterMode {
    NEAREST,
    LINEAR,
  }

  enum class MipmapMode {
    NONE,
    NEAREST,
    LINEAR,
  }

  class Sampling(
    var filter: bindings.Types.FilterMode,
    var mipmap: bindings.Types.MipmapMode,
  )
  /**
  A reusable fill/stroke source: gradients or an image pattern.
  Solid colors don't need a shader (use `paint.color`). Created via
  the `graphics` factory (draw interface) — all host-resident
  allocation flows through an embedder-granted handle, per WASI's
  no-ambient-authority principle.
  */
  class Shader : kotlin.AutoCloseable {
    internal var __handle: bindings.runtime.ResourceHandle = bindings.runtime.ResourceHandle(0)
    internal constructor(handle: bindings.runtime.ResourceHandle) { __handle = handle }
    override fun close() { __cm_resource_abi_import_Types_Shader_drop(__handle.value) }
    companion object {
    }
  }
  /**
  A decoded, host-resident image. Created via the `graphics` factory.
  */
  class Image : kotlin.AutoCloseable {
    internal var __handle: bindings.runtime.ResourceHandle = bindings.runtime.ResourceHandle(0)
    internal constructor(handle: bindings.runtime.ResourceHandle) { __handle = handle }
    override fun close() { __cm_resource_abi_import_Types_Image_drop(__handle.value) }
    fun width(): kotlin.UInt {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Int = __wasm_import_width(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return ret.toUInt()
      }
      // </editor-fold>
    }
    fun height(): kotlin.UInt {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Int = __wasm_import_height(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return ret.toUInt()
      }
      // </editor-fold>
    }
    companion object {
    }
  }

  /**
  Tint: combine each output pixel with `color` via `mode`
  (CSS/skia provenance: SkColorFilters::Blend; icon tinting is
  `mode = src-in`).
  */
  class ColorBlend(
    var color: kotlin.UInt,
    var mode: bindings.Types.BlendMode,
  )

  /**
  Color filter applied to the paint's output — after color/shader
  resolve, before blending into the destination.
  */
  sealed interface ColorFilter{ 
    class Blend(val value: bindings.Types.ColorBlend) : ColorFilter
    object Invert : ColorFilter
  }
  /**
  Per-draw styling. A value (not a resource): builder ergonomics live
  in guest bindings; the wire carries the resolved state. Used only
  as a parameter, so the `shader` borrow is canonical-ABI-legal.
  */
  class Paint(
    var style: bindings.Types.PaintStyle,
    /**
    Ignored when `shader` is set (the shader supplies color).
    */
    var color: kotlin.UInt,
    /**
    0..255 alpha multiplied onto color/shader output.
    */
    var alpha: kotlin.UByte,
    var blend: bindings.Types.BlendMode,
    var antiAlias: kotlin.Boolean,
    var shader: bindings.Types.Shader?,
    var strokeWidth: kotlin.Float,
    var strokeCap: bindings.Types.StrokeCap,
    var strokeJoin: bindings.Types.StrokeJoin,
    var strokeMiter: kotlin.Float,
    /**
    Mask blur (shadows/glows); none = sharp.
    */
    var blur: bindings.Types.MaskBlur?,
    /**
    Color filter (icon tinting, inversion); none = pass-through.
    */
    var filter: bindings.Types.ColorFilter?,
  )

  // END OF TYPES


}

@WitInterface("wasi:canvas/draw@0.0.2")
/*external */interface Draw {
  @WitImport
  companion object Import : bindings.Draw {
    // <editor-fold defaultstate="collapsed" desc="Generated Import Code">
    // </editor-fold>
  }
  // START OF TYPES

  /**
  A recorded, replayable display list (built via
  `graphics.start-recording` → draws → `canvas.finish-recording`).
  */
  class Picture : kotlin.AutoCloseable {
    internal var __handle: bindings.runtime.ResourceHandle = bindings.runtime.ResourceHandle(0)
    internal constructor(handle: bindings.runtime.ResourceHandle) { __handle = handle }
    override fun close() { __cm_resource_abi_import_Draw_Picture_drop(__handle.value) }
    companion object {
    }
  }
  /**
  The creation capability: every host-resident allocation (shaders,
  images, offscreen canvases, recordings) is a method here, so the
  EMBEDDER grants it explicitly (alongside the canvas) and may
  attenuate it (quotas, deny decode, …). Pure computation over the
  guest's own data stays out (e.g. typeface-from-bytes in the text
  package).
  */
  class Graphics : kotlin.AutoCloseable {
    internal var __handle: bindings.runtime.ResourceHandle = bindings.runtime.ResourceHandle(0)
    internal constructor(handle: bindings.runtime.ResourceHandle) { __handle = handle }
    override fun close() { __cm_resource_abi_import_Draw_Graphics_drop(__handle.value) }
    /**
    Linear gradient from `start` to `end`. `stops` are (offset in
    0..1, color) pairs, offsets ascending.
    */
    fun linearGradient(start: bindings.Types.Point, end: bindings.Types.Point, stops: kotlin.collections.List<kotlin.Pair<kotlin.Float, kotlin.UInt>>, tile: bindings.Types.TileMode, local: bindings.Types.Transform?): bindings.Types.Shader {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(56+4*4), align=4)*/ allocator.allocate((56+4*4)).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)
        (ptr + 4).ptr.storeFloat(start.x)
        (ptr + 8).ptr.storeFloat(start.y)
        (ptr + 12).ptr.storeFloat(end.x)
        (ptr + 16).ptr.storeFloat(end.y)

        val address = allocator.allocate(stops.size * 8 /*, align_wasm32=4*/).address.toInt()
        for ((index, el) in stops.withIndex()) {
          val base = address + (index * 8)
          (base + 0).ptr.storeFloat(el.first)
          (base + 4).ptr.storeInt(el.second.toInt())

        }
        (ptr + (16+2*4)).ptr.storeInt(stops.size)
        (ptr + (16+1*4)).ptr.storeInt(address)
        (ptr + (16+3*4)).ptr.storeByte(tile.ordinal.toByte())
        val payload0 = local
        if (payload0 != null) {
          (ptr + (20+3*4)).ptr.storeByte(1.toByte())
          (ptr + (24+3*4)).ptr.storeFloat(payload0.m00)
          (ptr + (28+3*4)).ptr.storeFloat(payload0.m01)
          (ptr + (32+3*4)).ptr.storeFloat(payload0.m02)
          (ptr + (36+3*4)).ptr.storeFloat(payload0.m10)
          (ptr + (40+3*4)).ptr.storeFloat(payload0.m11)
          (ptr + (44+3*4)).ptr.storeFloat(payload0.m12)
          (ptr + (48+3*4)).ptr.storeFloat(payload0.m20)
          (ptr + (52+3*4)).ptr.storeFloat(payload0.m21)
          (ptr + (56+3*4)).ptr.storeFloat(payload0.m22)
        } else {
          (ptr + (20+3*4)).ptr.storeByte(0.toByte())
        }
        val ret: kotlin.Int = __wasm_import_linearGradient(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val resource = bindings.Types.Shader(bindings.runtime.ResourceHandle(ret))
        return resource
      }
      // </editor-fold>
    }
    fun radialGradient(center: bindings.Types.Point, radius: kotlin.Float, stops: kotlin.collections.List<kotlin.Pair<kotlin.Float, kotlin.UInt>>, tile: bindings.Types.TileMode, local: bindings.Types.Transform?): bindings.Types.Shader {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(56+3*4), align=4)*/ allocator.allocate((56+3*4)).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)
        (ptr + 4).ptr.storeFloat(center.x)
        (ptr + 8).ptr.storeFloat(center.y)
        (ptr + 12).ptr.storeFloat(radius)

        val address = allocator.allocate(stops.size * 8 /*, align_wasm32=4*/).address.toInt()
        for ((index, el) in stops.withIndex()) {
          val base = address + (index * 8)
          (base + 0).ptr.storeFloat(el.first)
          (base + 4).ptr.storeInt(el.second.toInt())

        }
        (ptr + (16+1*4)).ptr.storeInt(stops.size)
        (ptr + 16).ptr.storeInt(address)
        (ptr + (16+2*4)).ptr.storeByte(tile.ordinal.toByte())
        val payload0 = local
        if (payload0 != null) {
          (ptr + (20+2*4)).ptr.storeByte(1.toByte())
          (ptr + (24+2*4)).ptr.storeFloat(payload0.m00)
          (ptr + (28+2*4)).ptr.storeFloat(payload0.m01)
          (ptr + (32+2*4)).ptr.storeFloat(payload0.m02)
          (ptr + (36+2*4)).ptr.storeFloat(payload0.m10)
          (ptr + (40+2*4)).ptr.storeFloat(payload0.m11)
          (ptr + (44+2*4)).ptr.storeFloat(payload0.m12)
          (ptr + (48+2*4)).ptr.storeFloat(payload0.m20)
          (ptr + (52+2*4)).ptr.storeFloat(payload0.m21)
          (ptr + (56+2*4)).ptr.storeFloat(payload0.m22)
        } else {
          (ptr + (20+2*4)).ptr.storeByte(0.toByte())
        }
        val ret: kotlin.Int = __wasm_import_radialGradient(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val resource = bindings.Types.Shader(bindings.runtime.ResourceHandle(ret))
        return resource
      }
      // </editor-fold>
    }
    /**
    Sweep (conic) gradient around `center`; angles in degrees,
    0° at the positive x-axis, increasing clockwise.
    */
    fun sweepGradient(center: bindings.Types.Point, startAngle: kotlin.Float, endAngle: kotlin.Float, stops: kotlin.collections.List<kotlin.Pair<kotlin.Float, kotlin.UInt>>, tile: bindings.Types.TileMode, local: bindings.Types.Transform?): bindings.Types.Shader {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(56+4*4), align=4)*/ allocator.allocate((56+4*4)).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)
        (ptr + 4).ptr.storeFloat(center.x)
        (ptr + 8).ptr.storeFloat(center.y)
        (ptr + 12).ptr.storeFloat(startAngle)
        (ptr + 16).ptr.storeFloat(endAngle)

        val address = allocator.allocate(stops.size * 8 /*, align_wasm32=4*/).address.toInt()
        for ((index, el) in stops.withIndex()) {
          val base = address + (index * 8)
          (base + 0).ptr.storeFloat(el.first)
          (base + 4).ptr.storeInt(el.second.toInt())

        }
        (ptr + (16+2*4)).ptr.storeInt(stops.size)
        (ptr + (16+1*4)).ptr.storeInt(address)
        (ptr + (16+3*4)).ptr.storeByte(tile.ordinal.toByte())
        val payload0 = local
        if (payload0 != null) {
          (ptr + (20+3*4)).ptr.storeByte(1.toByte())
          (ptr + (24+3*4)).ptr.storeFloat(payload0.m00)
          (ptr + (28+3*4)).ptr.storeFloat(payload0.m01)
          (ptr + (32+3*4)).ptr.storeFloat(payload0.m02)
          (ptr + (36+3*4)).ptr.storeFloat(payload0.m10)
          (ptr + (40+3*4)).ptr.storeFloat(payload0.m11)
          (ptr + (44+3*4)).ptr.storeFloat(payload0.m12)
          (ptr + (48+3*4)).ptr.storeFloat(payload0.m20)
          (ptr + (52+3*4)).ptr.storeFloat(payload0.m21)
          (ptr + (56+3*4)).ptr.storeFloat(payload0.m22)
        } else {
          (ptr + (20+3*4)).ptr.storeByte(0.toByte())
        }
        val ret: kotlin.Int = __wasm_import_sweepGradient(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val resource = bindings.Types.Shader(bindings.runtime.ResourceHandle(ret))
        return resource
      }
      // </editor-fold>
    }
    /**
    Image as a pattern, transformed by `local`, sampled with
    `sampling`, tiled per axis.
    */
    fun shaderBlend(mode: bindings.Types.BlendMode, dst: bindings.Types.Shader, src: bindings.Types.Shader): bindings.Types.Shader {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        var handle0 = dst.__handle.value;
        var handle1 = src.__handle.value;
        val ret: kotlin.Int = __wasm_import_shaderBlend(handle, mode.ordinal, handle0, handle1)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val resource = bindings.Types.Shader(bindings.runtime.ResourceHandle(ret))
        return resource
      }
      // </editor-fold>
    }
    fun imagePattern(image: bindings.Types.Image, tileX: bindings.Types.TileMode, tileY: bindings.Types.TileMode, sampling: bindings.Types.Sampling, local: bindings.Types.Transform): bindings.Types.Shader {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        var handle0 = image.__handle.value;
        val ret: kotlin.Int = __wasm_import_imagePattern(handle, handle0, tileX.ordinal, tileY.ordinal, sampling.filter.ordinal, sampling.mipmap.ordinal, local.m00, local.m01, local.m02, local.m10, local.m11, local.m12, local.m20, local.m21, local.m22)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val resource = bindings.Types.Shader(bindings.runtime.ResourceHandle(ret))
        return resource
      }
      // </editor-fold>
    }
    /**
    Decode PNG/JPEG/WebP/GIF(first frame)/BMP bytes. Errors on
    unrecognized or truncated data.
    */
    fun decodeImage(bytes: kotlin.collections.List<kotlin.UByte>): kotlin.Result<bindings.Types.Image> {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;

        val address = allocator.allocate(bytes.size * 1 /*, align_wasm32=1*/).address.toInt()
        for ((index, el) in bytes.withIndex()) {
          val base = address + (index * 1)
          (base + 0).ptr.storeByte(el.toInt().toByte())

        }
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=8, align=4)*/ allocator.allocate(8).address.toInt()
        __wasm_import_decodeImage(handle, address, bytes.size, ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val result = if ((ptr + 0).ptr.loadUByte().toInt()== 0) {
          val resource = bindings.Types.Image(bindings.runtime.ResourceHandle((ptr + 4).ptr.loadInt()))

          kotlin.Result.success<bindings.Types.Image>(resource)
        } else {
          kotlin.Result.failure<bindings.Types.Image>(bindings.runtime.ComponentException(kotlin.Unit))
        }
        return result
      }
      // </editor-fold>
    }
    /**
    Raw non-premultiplied RGBA8 pixels, tightly packed.
    */
    fun imageFromRgba8(width: kotlin.UInt, height: kotlin.UInt, pixels: kotlin.collections.List<kotlin.UByte>): kotlin.Result<bindings.Types.Image> {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;

        val address = allocator.allocate(pixels.size * 1 /*, align_wasm32=1*/).address.toInt()
        for ((index, el) in pixels.withIndex()) {
          val base = address + (index * 1)
          (base + 0).ptr.storeByte(el.toInt().toByte())

        }
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=8, align=4)*/ allocator.allocate(8).address.toInt()
        __wasm_import_imageFromRgba8(handle, width.toInt(), height.toInt(), address, pixels.size, ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val result = if ((ptr + 0).ptr.loadUByte().toInt()== 0) {
          val resource = bindings.Types.Image(bindings.runtime.ResourceHandle((ptr + 4).ptr.loadInt()))

          kotlin.Result.success<bindings.Types.Image>(resource)
        } else {
          kotlin.Result.failure<bindings.Types.Image>(bindings.runtime.ComponentException(kotlin.Unit))
        }
        return result
      }
      // </editor-fold>
    }
    /**
    A new offscreen raster canvas (layer caches, painters).
    */
    fun newOffscreen(width: kotlin.UInt, height: kotlin.UInt): bindings.Draw.Canvas {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Int = __wasm_import_newOffscreen(handle, width.toInt(), height.toInt())
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val resource = bindings.Draw.Canvas(bindings.runtime.ResourceHandle(ret))
        return resource
      }
      // </editor-fold>
    }
    /**
    Begin recording into a fresh display list; until
    `canvas.finish-recording`, draws on the returned canvas are
    captured, not rasterized.
    */
    fun startRecording(bounds: bindings.Types.Rect): bindings.Draw.Canvas {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Int = __wasm_import_startRecording(handle, bounds.x, bounds.y, bounds.width, bounds.height)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val resource = bindings.Draw.Canvas(bindings.runtime.ResourceHandle(ret))
        return resource
      }
      // </editor-fold>
    }
    companion object {
    }
  }
  class Canvas : kotlin.AutoCloseable {
    internal var __handle: bindings.runtime.ResourceHandle = bindings.runtime.ResourceHandle(0)
    internal constructor(handle: bindings.runtime.ResourceHandle) { __handle = handle }
    override fun close() { __cm_resource_abi_import_Draw_Canvas_drop(__handle.value) }
    /**
    Drawable size in canvas units (device-independent; the
    embedder defines the unit-to-pixel density out of band).
    */
    fun width(): kotlin.Float {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Float = __wasm_import_width0(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return ret
      }
      // </editor-fold>
    }
    fun height(): kotlin.Float {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Float = __wasm_import_height1(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return ret
      }
      // </editor-fold>
    }
    /**
    ── state stack ───────────────────────────────────────────────
    */
    fun save() {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_save(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    Composite everything until the matching `restore` through an
    offscreen layer with `alpha`, optionally bounded.
    */
    fun saveLayer(bounds: bindings.Types.Rect?, alpha: kotlin.UByte) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val option: kotlin.Int
        val option1: kotlin.Float
        val option2: kotlin.Float
        val option3: kotlin.Float
        val option4: kotlin.Float
        val payload0 = bounds
        if (payload0 != null) {
          option = 1
          option1 = payload0.x
          option2 = payload0.y
          option3 = payload0.width
          option4 = payload0.height
        } else {
          option = 0
          option1 = 0.0f
          option2 = 0.0f
          option3 = 0.0f
          option4 = 0.0f
        }
        __wasm_import_saveLayer(handle, option, option1, option2, option3, option4, alpha.toInt())
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun restore() {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_restore(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun translate(dx: kotlin.Float, dy: kotlin.Float) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_translate(handle, dx, dy)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun scale(sx: kotlin.Float, sy: kotlin.Float) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_scale(handle, sx, sy)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    Degrees clockwise.
    */
    fun rotate(degrees: kotlin.Float) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_rotate(handle, degrees)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun concat(t: bindings.Types.Transform) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_concat(handle, t.m00, t.m01, t.m02, t.m10, t.m11, t.m12, t.m20, t.m21, t.m22)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    ── clip (always intersects; save/restore scopes it) ──────────
    */
    fun clipRect(r: bindings.Types.Rect, antiAlias: kotlin.Boolean) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_clipRect(handle, r.x, r.y, r.width, r.height, (if(antiAlias) 1 else 0))
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun clipRoundedRect(rr: bindings.Types.RoundedRect, antiAlias: kotlin.Boolean) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_clipRoundedRect(handle, rr.rect.x, rr.rect.y, rr.rect.width, rr.rect.height, rr.topLeft.x, rr.topLeft.y, rr.topRight.x, rr.topRight.y, rr.bottomRight.x, rr.bottomRight.y, rr.bottomLeft.x, rr.bottomLeft.y, (if(antiAlias) 1 else 0))
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    `path` is an SVG path-data string
    (https://www.w3.org/TR/SVG2/paths.html#PathData).
    */
    fun clipPath(path: kotlin.String, rule: bindings.Types.FillRule, antiAlias: kotlin.Boolean) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;

        val bytearray = path.encodeToByteArray()
        val len = bytearray.size
        val ptr = allocator.writeToLinearMemory(bytearray).address.toInt()

        __wasm_import_clipPath(handle, ptr, len, rule.ordinal, (if(antiAlias) 1 else 0))
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    ── drawing ───────────────────────────────────────────────────
    Fill the whole clip with `color` (respecting blend).
    */
    fun clear(color: kotlin.UInt) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_clear(handle, color.toInt())
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun drawPaint(paint: bindings.Types.Paint) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=64, align=4)*/ allocator.allocate(64).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)
        (ptr + 4).ptr.storeByte(paint.style.ordinal.toByte())
        (ptr + 8).ptr.storeInt(paint.color.toInt())
        (ptr + 12).ptr.storeByte(paint.alpha.toInt().toByte())
        (ptr + 13).ptr.storeByte(paint.blend.ordinal.toByte())
        (ptr + 14).ptr.storeByte((if(paint.antiAlias) 1 else 0).toByte())
        val payload0 = paint.shader
        if (payload0 != null) {
          (ptr + 16).ptr.storeByte(1.toByte())
          var handle1 = payload0.__handle.value;
          (ptr + 20).ptr.storeInt(handle1)
        } else {
          (ptr + 16).ptr.storeByte(0.toByte())
        }
        (ptr + 24).ptr.storeFloat(paint.strokeWidth)
        (ptr + 28).ptr.storeByte(paint.strokeCap.ordinal.toByte())
        (ptr + 29).ptr.storeByte(paint.strokeJoin.ordinal.toByte())
        (ptr + 32).ptr.storeFloat(paint.strokeMiter)
        val payload3 = paint.blur
        if (payload3 != null) {
          (ptr + 36).ptr.storeByte(1.toByte())
          (ptr + 40).ptr.storeByte(payload3.style.ordinal.toByte())
          (ptr + 44).ptr.storeFloat(payload3.sigma)
        } else {
          (ptr + 36).ptr.storeByte(0.toByte())
        }
        val payload6 = paint.filter
        if (payload6 != null) {
          (ptr + 48).ptr.storeByte(1.toByte())
          // VariantLower START
          when (val x = payload6) {
            is bindings.Types.ColorFilter.Blend -> {
              val payload7 = x.value
              (ptr + 52).ptr.storeByte(0.toByte())
              (ptr + 56).ptr.storeInt(payload7.color.toInt())
              (ptr + 60).ptr.storeByte(payload7.mode.ordinal.toByte())
            }
            is bindings.Types.ColorFilter.Invert -> {
              (ptr + 52).ptr.storeByte(1.toByte())
            }
            else -> error("unreachable")
          }
          // VariantLower END
        } else {
          (ptr + 48).ptr.storeByte(0.toByte())
        }
        __wasm_import_drawPaint(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun drawRect(r: bindings.Types.Rect, paint: bindings.Types.Paint) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=80, align=4)*/ allocator.allocate(80).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)
        (ptr + 4).ptr.storeFloat(r.x)
        (ptr + 8).ptr.storeFloat(r.y)
        (ptr + 12).ptr.storeFloat(r.width)
        (ptr + 16).ptr.storeFloat(r.height)
        (ptr + 20).ptr.storeByte(paint.style.ordinal.toByte())
        (ptr + 24).ptr.storeInt(paint.color.toInt())
        (ptr + 28).ptr.storeByte(paint.alpha.toInt().toByte())
        (ptr + 29).ptr.storeByte(paint.blend.ordinal.toByte())
        (ptr + 30).ptr.storeByte((if(paint.antiAlias) 1 else 0).toByte())
        val payload0 = paint.shader
        if (payload0 != null) {
          (ptr + 32).ptr.storeByte(1.toByte())
          var handle1 = payload0.__handle.value;
          (ptr + 36).ptr.storeInt(handle1)
        } else {
          (ptr + 32).ptr.storeByte(0.toByte())
        }
        (ptr + 40).ptr.storeFloat(paint.strokeWidth)
        (ptr + 44).ptr.storeByte(paint.strokeCap.ordinal.toByte())
        (ptr + 45).ptr.storeByte(paint.strokeJoin.ordinal.toByte())
        (ptr + 48).ptr.storeFloat(paint.strokeMiter)
        val payload3 = paint.blur
        if (payload3 != null) {
          (ptr + 52).ptr.storeByte(1.toByte())
          (ptr + 56).ptr.storeByte(payload3.style.ordinal.toByte())
          (ptr + 60).ptr.storeFloat(payload3.sigma)
        } else {
          (ptr + 52).ptr.storeByte(0.toByte())
        }
        val payload6 = paint.filter
        if (payload6 != null) {
          (ptr + 64).ptr.storeByte(1.toByte())
          // VariantLower START
          when (val x = payload6) {
            is bindings.Types.ColorFilter.Blend -> {
              val payload7 = x.value
              (ptr + 68).ptr.storeByte(0.toByte())
              (ptr + 72).ptr.storeInt(payload7.color.toInt())
              (ptr + 76).ptr.storeByte(payload7.mode.ordinal.toByte())
            }
            is bindings.Types.ColorFilter.Invert -> {
              (ptr + 68).ptr.storeByte(1.toByte())
            }
            else -> error("unreachable")
          }
          // VariantLower END
        } else {
          (ptr + 64).ptr.storeByte(0.toByte())
        }
        __wasm_import_drawRect(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun drawRoundedRect(rr: bindings.Types.RoundedRect, paint: bindings.Types.Paint) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=112, align=4)*/ allocator.allocate(112).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)
        (ptr + 4).ptr.storeFloat(rr.rect.x)
        (ptr + 8).ptr.storeFloat(rr.rect.y)
        (ptr + 12).ptr.storeFloat(rr.rect.width)
        (ptr + 16).ptr.storeFloat(rr.rect.height)
        (ptr + 20).ptr.storeFloat(rr.topLeft.x)
        (ptr + 24).ptr.storeFloat(rr.topLeft.y)
        (ptr + 28).ptr.storeFloat(rr.topRight.x)
        (ptr + 32).ptr.storeFloat(rr.topRight.y)
        (ptr + 36).ptr.storeFloat(rr.bottomRight.x)
        (ptr + 40).ptr.storeFloat(rr.bottomRight.y)
        (ptr + 44).ptr.storeFloat(rr.bottomLeft.x)
        (ptr + 48).ptr.storeFloat(rr.bottomLeft.y)
        (ptr + 52).ptr.storeByte(paint.style.ordinal.toByte())
        (ptr + 56).ptr.storeInt(paint.color.toInt())
        (ptr + 60).ptr.storeByte(paint.alpha.toInt().toByte())
        (ptr + 61).ptr.storeByte(paint.blend.ordinal.toByte())
        (ptr + 62).ptr.storeByte((if(paint.antiAlias) 1 else 0).toByte())
        val payload0 = paint.shader
        if (payload0 != null) {
          (ptr + 64).ptr.storeByte(1.toByte())
          var handle1 = payload0.__handle.value;
          (ptr + 68).ptr.storeInt(handle1)
        } else {
          (ptr + 64).ptr.storeByte(0.toByte())
        }
        (ptr + 72).ptr.storeFloat(paint.strokeWidth)
        (ptr + 76).ptr.storeByte(paint.strokeCap.ordinal.toByte())
        (ptr + 77).ptr.storeByte(paint.strokeJoin.ordinal.toByte())
        (ptr + 80).ptr.storeFloat(paint.strokeMiter)
        val payload3 = paint.blur
        if (payload3 != null) {
          (ptr + 84).ptr.storeByte(1.toByte())
          (ptr + 88).ptr.storeByte(payload3.style.ordinal.toByte())
          (ptr + 92).ptr.storeFloat(payload3.sigma)
        } else {
          (ptr + 84).ptr.storeByte(0.toByte())
        }
        val payload6 = paint.filter
        if (payload6 != null) {
          (ptr + 96).ptr.storeByte(1.toByte())
          // VariantLower START
          when (val x = payload6) {
            is bindings.Types.ColorFilter.Blend -> {
              val payload7 = x.value
              (ptr + 100).ptr.storeByte(0.toByte())
              (ptr + 104).ptr.storeInt(payload7.color.toInt())
              (ptr + 108).ptr.storeByte(payload7.mode.ordinal.toByte())
            }
            is bindings.Types.ColorFilter.Invert -> {
              (ptr + 100).ptr.storeByte(1.toByte())
            }
            else -> error("unreachable")
          }
          // VariantLower END
        } else {
          (ptr + 96).ptr.storeByte(0.toByte())
        }
        __wasm_import_drawRoundedRect(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    Outer rounded rect minus inner (borders/donuts).
    */
    fun drawDoubleRoundedRect(outer: bindings.Types.RoundedRect, inner: bindings.Types.RoundedRect, paint: bindings.Types.Paint) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=160, align=4)*/ allocator.allocate(160).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)
        (ptr + 4).ptr.storeFloat(outer.rect.x)
        (ptr + 8).ptr.storeFloat(outer.rect.y)
        (ptr + 12).ptr.storeFloat(outer.rect.width)
        (ptr + 16).ptr.storeFloat(outer.rect.height)
        (ptr + 20).ptr.storeFloat(outer.topLeft.x)
        (ptr + 24).ptr.storeFloat(outer.topLeft.y)
        (ptr + 28).ptr.storeFloat(outer.topRight.x)
        (ptr + 32).ptr.storeFloat(outer.topRight.y)
        (ptr + 36).ptr.storeFloat(outer.bottomRight.x)
        (ptr + 40).ptr.storeFloat(outer.bottomRight.y)
        (ptr + 44).ptr.storeFloat(outer.bottomLeft.x)
        (ptr + 48).ptr.storeFloat(outer.bottomLeft.y)
        (ptr + 52).ptr.storeFloat(inner.rect.x)
        (ptr + 56).ptr.storeFloat(inner.rect.y)
        (ptr + 60).ptr.storeFloat(inner.rect.width)
        (ptr + 64).ptr.storeFloat(inner.rect.height)
        (ptr + 68).ptr.storeFloat(inner.topLeft.x)
        (ptr + 72).ptr.storeFloat(inner.topLeft.y)
        (ptr + 76).ptr.storeFloat(inner.topRight.x)
        (ptr + 80).ptr.storeFloat(inner.topRight.y)
        (ptr + 84).ptr.storeFloat(inner.bottomRight.x)
        (ptr + 88).ptr.storeFloat(inner.bottomRight.y)
        (ptr + 92).ptr.storeFloat(inner.bottomLeft.x)
        (ptr + 96).ptr.storeFloat(inner.bottomLeft.y)
        (ptr + 100).ptr.storeByte(paint.style.ordinal.toByte())
        (ptr + 104).ptr.storeInt(paint.color.toInt())
        (ptr + 108).ptr.storeByte(paint.alpha.toInt().toByte())
        (ptr + 109).ptr.storeByte(paint.blend.ordinal.toByte())
        (ptr + 110).ptr.storeByte((if(paint.antiAlias) 1 else 0).toByte())
        val payload0 = paint.shader
        if (payload0 != null) {
          (ptr + 112).ptr.storeByte(1.toByte())
          var handle1 = payload0.__handle.value;
          (ptr + 116).ptr.storeInt(handle1)
        } else {
          (ptr + 112).ptr.storeByte(0.toByte())
        }
        (ptr + 120).ptr.storeFloat(paint.strokeWidth)
        (ptr + 124).ptr.storeByte(paint.strokeCap.ordinal.toByte())
        (ptr + 125).ptr.storeByte(paint.strokeJoin.ordinal.toByte())
        (ptr + 128).ptr.storeFloat(paint.strokeMiter)
        val payload3 = paint.blur
        if (payload3 != null) {
          (ptr + 132).ptr.storeByte(1.toByte())
          (ptr + 136).ptr.storeByte(payload3.style.ordinal.toByte())
          (ptr + 140).ptr.storeFloat(payload3.sigma)
        } else {
          (ptr + 132).ptr.storeByte(0.toByte())
        }
        val payload6 = paint.filter
        if (payload6 != null) {
          (ptr + 144).ptr.storeByte(1.toByte())
          // VariantLower START
          when (val x = payload6) {
            is bindings.Types.ColorFilter.Blend -> {
              val payload7 = x.value
              (ptr + 148).ptr.storeByte(0.toByte())
              (ptr + 152).ptr.storeInt(payload7.color.toInt())
              (ptr + 156).ptr.storeByte(payload7.mode.ordinal.toByte())
            }
            is bindings.Types.ColorFilter.Invert -> {
              (ptr + 148).ptr.storeByte(1.toByte())
            }
            else -> error("unreachable")
          }
          // VariantLower END
        } else {
          (ptr + 144).ptr.storeByte(0.toByte())
        }
        __wasm_import_drawDoubleRoundedRect(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun drawOval(bounds: bindings.Types.Rect, paint: bindings.Types.Paint) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=80, align=4)*/ allocator.allocate(80).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)
        (ptr + 4).ptr.storeFloat(bounds.x)
        (ptr + 8).ptr.storeFloat(bounds.y)
        (ptr + 12).ptr.storeFloat(bounds.width)
        (ptr + 16).ptr.storeFloat(bounds.height)
        (ptr + 20).ptr.storeByte(paint.style.ordinal.toByte())
        (ptr + 24).ptr.storeInt(paint.color.toInt())
        (ptr + 28).ptr.storeByte(paint.alpha.toInt().toByte())
        (ptr + 29).ptr.storeByte(paint.blend.ordinal.toByte())
        (ptr + 30).ptr.storeByte((if(paint.antiAlias) 1 else 0).toByte())
        val payload0 = paint.shader
        if (payload0 != null) {
          (ptr + 32).ptr.storeByte(1.toByte())
          var handle1 = payload0.__handle.value;
          (ptr + 36).ptr.storeInt(handle1)
        } else {
          (ptr + 32).ptr.storeByte(0.toByte())
        }
        (ptr + 40).ptr.storeFloat(paint.strokeWidth)
        (ptr + 44).ptr.storeByte(paint.strokeCap.ordinal.toByte())
        (ptr + 45).ptr.storeByte(paint.strokeJoin.ordinal.toByte())
        (ptr + 48).ptr.storeFloat(paint.strokeMiter)
        val payload3 = paint.blur
        if (payload3 != null) {
          (ptr + 52).ptr.storeByte(1.toByte())
          (ptr + 56).ptr.storeByte(payload3.style.ordinal.toByte())
          (ptr + 60).ptr.storeFloat(payload3.sigma)
        } else {
          (ptr + 52).ptr.storeByte(0.toByte())
        }
        val payload6 = paint.filter
        if (payload6 != null) {
          (ptr + 64).ptr.storeByte(1.toByte())
          // VariantLower START
          when (val x = payload6) {
            is bindings.Types.ColorFilter.Blend -> {
              val payload7 = x.value
              (ptr + 68).ptr.storeByte(0.toByte())
              (ptr + 72).ptr.storeInt(payload7.color.toInt())
              (ptr + 76).ptr.storeByte(payload7.mode.ordinal.toByte())
            }
            is bindings.Types.ColorFilter.Invert -> {
              (ptr + 68).ptr.storeByte(1.toByte())
            }
            else -> error("unreachable")
          }
          // VariantLower END
        } else {
          (ptr + 64).ptr.storeByte(0.toByte())
        }
        __wasm_import_drawOval(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun drawLine(start: bindings.Types.Point, end: bindings.Types.Point, paint: bindings.Types.Paint) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=80, align=4)*/ allocator.allocate(80).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)
        (ptr + 4).ptr.storeFloat(start.x)
        (ptr + 8).ptr.storeFloat(start.y)
        (ptr + 12).ptr.storeFloat(end.x)
        (ptr + 16).ptr.storeFloat(end.y)
        (ptr + 20).ptr.storeByte(paint.style.ordinal.toByte())
        (ptr + 24).ptr.storeInt(paint.color.toInt())
        (ptr + 28).ptr.storeByte(paint.alpha.toInt().toByte())
        (ptr + 29).ptr.storeByte(paint.blend.ordinal.toByte())
        (ptr + 30).ptr.storeByte((if(paint.antiAlias) 1 else 0).toByte())
        val payload0 = paint.shader
        if (payload0 != null) {
          (ptr + 32).ptr.storeByte(1.toByte())
          var handle1 = payload0.__handle.value;
          (ptr + 36).ptr.storeInt(handle1)
        } else {
          (ptr + 32).ptr.storeByte(0.toByte())
        }
        (ptr + 40).ptr.storeFloat(paint.strokeWidth)
        (ptr + 44).ptr.storeByte(paint.strokeCap.ordinal.toByte())
        (ptr + 45).ptr.storeByte(paint.strokeJoin.ordinal.toByte())
        (ptr + 48).ptr.storeFloat(paint.strokeMiter)
        val payload3 = paint.blur
        if (payload3 != null) {
          (ptr + 52).ptr.storeByte(1.toByte())
          (ptr + 56).ptr.storeByte(payload3.style.ordinal.toByte())
          (ptr + 60).ptr.storeFloat(payload3.sigma)
        } else {
          (ptr + 52).ptr.storeByte(0.toByte())
        }
        val payload6 = paint.filter
        if (payload6 != null) {
          (ptr + 64).ptr.storeByte(1.toByte())
          // VariantLower START
          when (val x = payload6) {
            is bindings.Types.ColorFilter.Blend -> {
              val payload7 = x.value
              (ptr + 68).ptr.storeByte(0.toByte())
              (ptr + 72).ptr.storeInt(payload7.color.toInt())
              (ptr + 76).ptr.storeByte(payload7.mode.ordinal.toByte())
            }
            is bindings.Types.ColorFilter.Invert -> {
              (ptr + 68).ptr.storeByte(1.toByte())
            }
            else -> error("unreachable")
          }
          // VariantLower END
        } else {
          (ptr + 64).ptr.storeByte(0.toByte())
        }
        __wasm_import_drawLine(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    Arc of the oval inscribed in `bounds`; angles in degrees,
    0° at the positive x-axis, increasing clockwise.
    */
    fun drawArc(bounds: bindings.Types.Rect, startAngle: kotlin.Float, sweepAngle: kotlin.Float, includeCenter: kotlin.Boolean, paint: bindings.Types.Paint) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=92, align=4)*/ allocator.allocate(92).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)
        (ptr + 4).ptr.storeFloat(bounds.x)
        (ptr + 8).ptr.storeFloat(bounds.y)
        (ptr + 12).ptr.storeFloat(bounds.width)
        (ptr + 16).ptr.storeFloat(bounds.height)
        (ptr + 20).ptr.storeFloat(startAngle)
        (ptr + 24).ptr.storeFloat(sweepAngle)
        (ptr + 28).ptr.storeByte((if(includeCenter) 1 else 0).toByte())
        (ptr + 32).ptr.storeByte(paint.style.ordinal.toByte())
        (ptr + 36).ptr.storeInt(paint.color.toInt())
        (ptr + 40).ptr.storeByte(paint.alpha.toInt().toByte())
        (ptr + 41).ptr.storeByte(paint.blend.ordinal.toByte())
        (ptr + 42).ptr.storeByte((if(paint.antiAlias) 1 else 0).toByte())
        val payload0 = paint.shader
        if (payload0 != null) {
          (ptr + 44).ptr.storeByte(1.toByte())
          var handle1 = payload0.__handle.value;
          (ptr + 48).ptr.storeInt(handle1)
        } else {
          (ptr + 44).ptr.storeByte(0.toByte())
        }
        (ptr + 52).ptr.storeFloat(paint.strokeWidth)
        (ptr + 56).ptr.storeByte(paint.strokeCap.ordinal.toByte())
        (ptr + 57).ptr.storeByte(paint.strokeJoin.ordinal.toByte())
        (ptr + 60).ptr.storeFloat(paint.strokeMiter)
        val payload3 = paint.blur
        if (payload3 != null) {
          (ptr + 64).ptr.storeByte(1.toByte())
          (ptr + 68).ptr.storeByte(payload3.style.ordinal.toByte())
          (ptr + 72).ptr.storeFloat(payload3.sigma)
        } else {
          (ptr + 64).ptr.storeByte(0.toByte())
        }
        val payload6 = paint.filter
        if (payload6 != null) {
          (ptr + 76).ptr.storeByte(1.toByte())
          // VariantLower START
          when (val x = payload6) {
            is bindings.Types.ColorFilter.Blend -> {
              val payload7 = x.value
              (ptr + 80).ptr.storeByte(0.toByte())
              (ptr + 84).ptr.storeInt(payload7.color.toInt())
              (ptr + 88).ptr.storeByte(payload7.mode.ordinal.toByte())
            }
            is bindings.Types.ColorFilter.Invert -> {
              (ptr + 80).ptr.storeByte(1.toByte())
            }
            else -> error("unreachable")
          }
          // VariantLower END
        } else {
          (ptr + 76).ptr.storeByte(0.toByte())
        }
        __wasm_import_drawArc(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    SVG path-data string, filled/stroked per `paint.style`.
    */
    fun drawPath(path: kotlin.String, rule: bindings.Types.FillRule, paint: bindings.Types.Paint) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(64+3*4), align=4)*/ allocator.allocate((64+3*4)).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)

        val bytearray = path.encodeToByteArray()
        val len = bytearray.size
        val ptr0 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (2*4)).ptr.storeInt(len)
        (ptr + 4).ptr.storeInt(ptr0)
        (ptr + (3*4)).ptr.storeByte(rule.ordinal.toByte())
        (ptr + (4+3*4)).ptr.storeByte(paint.style.ordinal.toByte())
        (ptr + (8+3*4)).ptr.storeInt(paint.color.toInt())
        (ptr + (12+3*4)).ptr.storeByte(paint.alpha.toInt().toByte())
        (ptr + (13+3*4)).ptr.storeByte(paint.blend.ordinal.toByte())
        (ptr + (14+3*4)).ptr.storeByte((if(paint.antiAlias) 1 else 0).toByte())
        val payload1 = paint.shader
        if (payload1 != null) {
          (ptr + (16+3*4)).ptr.storeByte(1.toByte())
          var handle2 = payload1.__handle.value;
          (ptr + (20+3*4)).ptr.storeInt(handle2)
        } else {
          (ptr + (16+3*4)).ptr.storeByte(0.toByte())
        }
        (ptr + (24+3*4)).ptr.storeFloat(paint.strokeWidth)
        (ptr + (28+3*4)).ptr.storeByte(paint.strokeCap.ordinal.toByte())
        (ptr + (29+3*4)).ptr.storeByte(paint.strokeJoin.ordinal.toByte())
        (ptr + (32+3*4)).ptr.storeFloat(paint.strokeMiter)
        val payload4 = paint.blur
        if (payload4 != null) {
          (ptr + (36+3*4)).ptr.storeByte(1.toByte())
          (ptr + (40+3*4)).ptr.storeByte(payload4.style.ordinal.toByte())
          (ptr + (44+3*4)).ptr.storeFloat(payload4.sigma)
        } else {
          (ptr + (36+3*4)).ptr.storeByte(0.toByte())
        }
        val payload7 = paint.filter
        if (payload7 != null) {
          (ptr + (48+3*4)).ptr.storeByte(1.toByte())
          // VariantLower START
          when (val x = payload7) {
            is bindings.Types.ColorFilter.Blend -> {
              val payload8 = x.value
              (ptr + (52+3*4)).ptr.storeByte(0.toByte())
              (ptr + (56+3*4)).ptr.storeInt(payload8.color.toInt())
              (ptr + (60+3*4)).ptr.storeByte(payload8.mode.ordinal.toByte())
            }
            is bindings.Types.ColorFilter.Invert -> {
              (ptr + (52+3*4)).ptr.storeByte(1.toByte())
            }
            else -> error("unreachable")
          }
          // VariantLower END
        } else {
          (ptr + (48+3*4)).ptr.storeByte(0.toByte())
        }
        __wasm_import_drawPath(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun drawImage(image: bindings.Types.Image, at: bindings.Types.Point, sampling: bindings.Types.Sampling, paint: bindings.Types.Paint) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=80, align=4)*/ allocator.allocate(80).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)
        var handle0 = image.__handle.value;
        (ptr + 4).ptr.storeInt(handle0)
        (ptr + 8).ptr.storeFloat(at.x)
        (ptr + 12).ptr.storeFloat(at.y)
        (ptr + 16).ptr.storeByte(sampling.filter.ordinal.toByte())
        (ptr + 17).ptr.storeByte(sampling.mipmap.ordinal.toByte())
        (ptr + 20).ptr.storeByte(paint.style.ordinal.toByte())
        (ptr + 24).ptr.storeInt(paint.color.toInt())
        (ptr + 28).ptr.storeByte(paint.alpha.toInt().toByte())
        (ptr + 29).ptr.storeByte(paint.blend.ordinal.toByte())
        (ptr + 30).ptr.storeByte((if(paint.antiAlias) 1 else 0).toByte())
        val payload1 = paint.shader
        if (payload1 != null) {
          (ptr + 32).ptr.storeByte(1.toByte())
          var handle2 = payload1.__handle.value;
          (ptr + 36).ptr.storeInt(handle2)
        } else {
          (ptr + 32).ptr.storeByte(0.toByte())
        }
        (ptr + 40).ptr.storeFloat(paint.strokeWidth)
        (ptr + 44).ptr.storeByte(paint.strokeCap.ordinal.toByte())
        (ptr + 45).ptr.storeByte(paint.strokeJoin.ordinal.toByte())
        (ptr + 48).ptr.storeFloat(paint.strokeMiter)
        val payload4 = paint.blur
        if (payload4 != null) {
          (ptr + 52).ptr.storeByte(1.toByte())
          (ptr + 56).ptr.storeByte(payload4.style.ordinal.toByte())
          (ptr + 60).ptr.storeFloat(payload4.sigma)
        } else {
          (ptr + 52).ptr.storeByte(0.toByte())
        }
        val payload7 = paint.filter
        if (payload7 != null) {
          (ptr + 64).ptr.storeByte(1.toByte())
          // VariantLower START
          when (val x = payload7) {
            is bindings.Types.ColorFilter.Blend -> {
              val payload8 = x.value
              (ptr + 68).ptr.storeByte(0.toByte())
              (ptr + 72).ptr.storeInt(payload8.color.toInt())
              (ptr + 76).ptr.storeByte(payload8.mode.ordinal.toByte())
            }
            is bindings.Types.ColorFilter.Invert -> {
              (ptr + 68).ptr.storeByte(1.toByte())
            }
            else -> error("unreachable")
          }
          // VariantLower END
        } else {
          (ptr + 64).ptr.storeByte(0.toByte())
        }
        __wasm_import_drawImage(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    Draw `src` (image pixels) into `dst` (canvas units).
    */
    fun drawImageRect(image: bindings.Types.Image, src: bindings.Types.Rect, dst: bindings.Types.Rect, sampling: bindings.Types.Sampling, paint: bindings.Types.Paint) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=104, align=4)*/ allocator.allocate(104).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)
        var handle0 = image.__handle.value;
        (ptr + 4).ptr.storeInt(handle0)
        (ptr + 8).ptr.storeFloat(src.x)
        (ptr + 12).ptr.storeFloat(src.y)
        (ptr + 16).ptr.storeFloat(src.width)
        (ptr + 20).ptr.storeFloat(src.height)
        (ptr + 24).ptr.storeFloat(dst.x)
        (ptr + 28).ptr.storeFloat(dst.y)
        (ptr + 32).ptr.storeFloat(dst.width)
        (ptr + 36).ptr.storeFloat(dst.height)
        (ptr + 40).ptr.storeByte(sampling.filter.ordinal.toByte())
        (ptr + 41).ptr.storeByte(sampling.mipmap.ordinal.toByte())
        (ptr + 44).ptr.storeByte(paint.style.ordinal.toByte())
        (ptr + 48).ptr.storeInt(paint.color.toInt())
        (ptr + 52).ptr.storeByte(paint.alpha.toInt().toByte())
        (ptr + 53).ptr.storeByte(paint.blend.ordinal.toByte())
        (ptr + 54).ptr.storeByte((if(paint.antiAlias) 1 else 0).toByte())
        val payload1 = paint.shader
        if (payload1 != null) {
          (ptr + 56).ptr.storeByte(1.toByte())
          var handle2 = payload1.__handle.value;
          (ptr + 60).ptr.storeInt(handle2)
        } else {
          (ptr + 56).ptr.storeByte(0.toByte())
        }
        (ptr + 64).ptr.storeFloat(paint.strokeWidth)
        (ptr + 68).ptr.storeByte(paint.strokeCap.ordinal.toByte())
        (ptr + 69).ptr.storeByte(paint.strokeJoin.ordinal.toByte())
        (ptr + 72).ptr.storeFloat(paint.strokeMiter)
        val payload4 = paint.blur
        if (payload4 != null) {
          (ptr + 76).ptr.storeByte(1.toByte())
          (ptr + 80).ptr.storeByte(payload4.style.ordinal.toByte())
          (ptr + 84).ptr.storeFloat(payload4.sigma)
        } else {
          (ptr + 76).ptr.storeByte(0.toByte())
        }
        val payload7 = paint.filter
        if (payload7 != null) {
          (ptr + 88).ptr.storeByte(1.toByte())
          // VariantLower START
          when (val x = payload7) {
            is bindings.Types.ColorFilter.Blend -> {
              val payload8 = x.value
              (ptr + 92).ptr.storeByte(0.toByte())
              (ptr + 96).ptr.storeInt(payload8.color.toInt())
              (ptr + 100).ptr.storeByte(payload8.mode.ordinal.toByte())
            }
            is bindings.Types.ColorFilter.Invert -> {
              (ptr + 92).ptr.storeByte(1.toByte())
            }
            else -> error("unreachable")
          }
          // VariantLower END
        } else {
          (ptr + 88).ptr.storeByte(0.toByte())
        }
        __wasm_import_drawImageRect(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun drawPicture(p: bindings.Draw.Picture) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        var handle0 = p.__handle.value;
        __wasm_import_drawPicture(handle, handle0)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    Snapshot an offscreen canvas's pixels as an image (errors on
    the embedder-presented canvas — its pixels stay private).
    */
    fun snapshot(): kotlin.Result<bindings.Types.Image> {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=8, align=4)*/ allocator.allocate(8).address.toInt()
        __wasm_import_snapshot(handle, ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val result = if ((ptr + 0).ptr.loadUByte().toInt()== 0) {
          val resource = bindings.Types.Image(bindings.runtime.ResourceHandle((ptr + 4).ptr.loadInt()))

          kotlin.Result.success<bindings.Types.Image>(resource)
        } else {
          kotlin.Result.failure<bindings.Types.Image>(bindings.runtime.ComponentException(kotlin.Unit))
        }
        return result
      }
      // </editor-fold>
    }
    companion object {
      /**
      ── pictures (recorded display lists) ────────────────────────
      Finish a recording canvas (consumes it; from
      `graphics.start-recording`). Static-with-handle: the consumed
      canvas IS the capability.
      */
      fun finishRecording(c: bindings.Draw.Canvas): bindings.Draw.Picture {
        // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
        kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
          var handle = c.__handle.value;
          c.__handle = bindings.runtime.ResourceHandle(0);
          val ret: kotlin.Int = __wasm_import_finishRecording(handle)
          kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
          val resource = bindings.Draw.Picture(bindings.runtime.ResourceHandle(ret))
          return resource
        }
        // </editor-fold>
      }
    }
  }

  // END OF TYPES


}

@WitInterface("wasi:canvas/layout@0.0.2")
/*external */interface Layout {
  @WitImport
  companion object Import : bindings.Layout {
    // <editor-fold defaultstate="collapsed" desc="Generated Import Code">
    // </editor-fold>
  }
  // START OF TYPES


  enum class DecorationLineStyle {
    SOLID,
    DOUBLE,
    DOTTED,
    DASHED,
    WAVY,
  }

  /**
  Text decorations (Compose TextDecoration, dart:ui decorations).
  */
  class Decoration(
    var underline: kotlin.Boolean,
    var overline: kotlin.Boolean,
    var lineThrough: kotlin.Boolean,
    /**
    0 = use the text color.
    */
    var color: kotlin.UInt,
    var style: bindings.Layout.DecorationLineStyle,
    /**
    Multiple of the font-suggested thickness.
    */
    var thickness: kotlin.Float,
  )

  class TextShadow(
    var color: kotlin.UInt,
    var offset: bindings.Types.Point,
    var sigma: kotlin.Float,
  )

  class TextStyle(
    /**
    Font family name resolved by the HOST's font collection
    (host-owned fonts is the point of this layer). Empty = default.
    */
    var family: kotlin.String,
    var size: kotlin.Float,
    /**
    CSS-numeric weight (400 normal, 700 bold).
    */
    var weight: kotlin.UInt,
    var italic: kotlin.Boolean,
    var color: kotlin.UInt,
    var letterSpacing: kotlin.Float,
    /**
    Line height as a multiple of the font size; 0 = font default.
    */
    var lineHeight: kotlin.Float,
    /**
    Vertical run shift (superscript/subscript); 0 = none.
    */
    var baselineShift: kotlin.Float,
    var decoration: bindings.Layout.Decoration?,
    /**
    Empty = none (a LIST — dart:ui carries multiple per span).
    */
    var shadows: kotlin.collections.List<bindings.Layout.TextShadow>,
    var background: kotlin.UInt?,
  )

  enum class Align {
    START,
    CENTER,
    END,
    JUSTIFY,
  }

  /**
  Per-line metrics — the full editor-grade shape (cursor placement,
  line hit-testing). Field provenance: skia textlayout LineMetrics,
  which is what every shipped host-shaping engine exposes.
  */
  class LineMetrics(
    var startOffset: kotlin.UInt,
    /**
    UTF-8 byte offsets into the paragraph text
    */
    var endOffset: kotlin.UInt,
    /**
    `end-offset` with trailing whitespace excluded.
    */
    var endExcludingWhitespace: kotlin.UInt,
    /**
    `end-offset` including a trailing hard-break newline.
    */
    var endIncludingNewline: kotlin.UInt,
    /**
    True when the line ends in an explicit newline.
    */
    var hardBreak: kotlin.Boolean,
    var ascent: kotlin.Float,
    var descent: kotlin.Float,
    /**
    Ascent before any line-height multiplier.
    */
    var unscaledAscent: kotlin.Float,
    var height: kotlin.Float,
    var width: kotlin.Float,
    var left: kotlin.Float,
    var baseline: kotlin.Float,
    var lineNumber: kotlin.UInt,
  )

  enum class TextDirection {
    LTR,
    RTL,
  }

  /**
  How tall the rects returned by `selection-boxes` are (CSS caret /
  selection-highlight distinctions; skparagraph RectHeightStyle).
  */
  enum class RectHeightStyle {
    TIGHT,
    MAX,
    INCLUDE_LINE_SPACING_MIDDLE,
    INCLUDE_LINE_SPACING_TOP,
    INCLUDE_LINE_SPACING_BOTTOM,
    STRUT,
  }

  enum class RectWidthStyle {
    TIGHT,
    MAX,
  }

  class TextBox(
    var rect: bindings.Types.Rect,
    var direction: bindings.Layout.TextDirection,
  )
  class Paragraph : kotlin.AutoCloseable {
    internal var __handle: bindings.runtime.ResourceHandle = bindings.runtime.ResourceHandle(0)
    internal constructor(handle: bindings.runtime.ResourceHandle) { __handle = handle }
    override fun close() { __cm_resource_abi_import_Layout_Paragraph_drop(__handle.value) }
    fun layout(width: kotlin.Float) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_layout(handle, width)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun paint(canvas: bindings.Draw.Canvas, at: bindings.Types.Point) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        var handle0 = canvas.__handle.value;
        __wasm_import_paint(handle, handle0, at.x, at.y)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun height(): kotlin.Float {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Float = __wasm_import_height2(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return ret
      }
      // </editor-fold>
    }
    fun maxIntrinsicWidth(): kotlin.Float {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Float = __wasm_import_maxIntrinsicWidth(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return ret
      }
      // </editor-fold>
    }
    fun minIntrinsicWidth(): kotlin.Float {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Float = __wasm_import_minIntrinsicWidth(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return ret
      }
      // </editor-fold>
    }
    fun alphabeticBaseline(): kotlin.Float {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Float = __wasm_import_alphabeticBaseline(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return ret
      }
      // </editor-fold>
    }
    fun ideographicBaseline(): kotlin.Float {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Float = __wasm_import_ideographicBaseline(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return ret
      }
      // </editor-fold>
    }
    fun lineCount(): kotlin.UInt {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Int = __wasm_import_lineCount(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return ret.toUInt()
      }
      // </editor-fold>
    }
    fun lines(): kotlin.collections.List<bindings.Layout.LineMetrics> {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(2*4), align=4)*/ allocator.allocate((2*4)).address.toInt()
        __wasm_import_lines(handle, ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();

        val list = kotlin.collections.ArrayList<bindings.Layout.LineMetrics>((ptr + 4).ptr.loadInt())
        for (i in 0 until (ptr + 4).ptr.loadInt()) {
          val base = ((ptr + 0).ptr.loadInt()) + (i * 52)
          
          list.add(bindings.Layout.LineMetrics(
          (base + 0).ptr.loadInt().toUInt(),
          (base + 4).ptr.loadInt().toUInt(),
          (base + 8).ptr.loadInt().toUInt(),
          (base + 12).ptr.loadInt().toUInt(),
          ((base + 16).ptr.loadUByte().toInt() != 0),
          (base + 20).ptr.loadFloat(),
          (base + 24).ptr.loadFloat(),
          (base + 28).ptr.loadFloat(),
          (base + 32).ptr.loadFloat(),
          (base + 36).ptr.loadFloat(),
          (base + 40).ptr.loadFloat(),
          (base + 44).ptr.loadFloat(),
          (base + 48).ptr.loadInt().toUInt(),
          ))
        }
        return list
      }
      // </editor-fold>
    }
    /**
    Caret/selection geometry for a UTF-8 byte range, with the
    box-shape policy callers like text editors need.
    */
    fun selectionBoxes(start: kotlin.UInt, end: kotlin.UInt, height: bindings.Layout.RectHeightStyle, width: bindings.Layout.RectWidthStyle): kotlin.collections.List<bindings.Layout.TextBox> {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(2*4), align=4)*/ allocator.allocate((2*4)).address.toInt()
        __wasm_import_selectionBoxes(handle, start.toInt(), end.toInt(), height.ordinal, width.ordinal, ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();

        val list = kotlin.collections.ArrayList<bindings.Layout.TextBox>((ptr + 4).ptr.loadInt())
        for (i in 0 until (ptr + 4).ptr.loadInt()) {
          val base = ((ptr + 0).ptr.loadInt()) + (i * 20)
          
          list.add(bindings.Layout.TextBox(
          bindings.Types.Rect(
          (base + 0).ptr.loadFloat(),
          (base + 4).ptr.loadFloat(),
          (base + 8).ptr.loadFloat(),
          (base + 12).ptr.loadFloat(),
          ),
          bindings.Layout.TextDirection.values()[(base + 16).ptr.loadUByte().toInt()],
          ))
        }
        return list
      }
      // </editor-fold>
    }
    /**
    Nearest text position (UTF-8 byte offset) to a point.
    */
    fun offsetAt(at: bindings.Types.Point): kotlin.UInt {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Int = __wasm_import_offsetAt(handle, at.x, at.y)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return ret.toUInt()
      }
      // </editor-fold>
    }
    /**
    [start, end) of the word containing `offset`.
    */
    fun wordBoundary(offset: kotlin.UInt): kotlin.Pair<kotlin.UInt, kotlin.UInt> {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=8, align=4)*/ allocator.allocate(8).address.toInt()
        __wasm_import_wordBoundary(handle, offset.toInt(), ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return kotlin.Pair<kotlin.UInt, kotlin.UInt>(
        (ptr + 0).ptr.loadInt().toUInt(),
        (ptr + 4).ptr.loadInt().toUInt(),
        )
      }
      // </editor-fold>
    }
    /**
    True when max-lines truncated the layout.
    */
    fun didExceedMaxLines(): kotlin.Boolean {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Int = __wasm_import_didExceedMaxLines(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        return (ret != 0)
      }
      // </editor-fold>
    }
    companion object {
    }
  }
  /**
  Setter form (R2): paragraph-wide options are methods, so the
  next option is additive instead of a constructor break.
  */
  class ParagraphBuilder : kotlin.AutoCloseable {
    internal var __handle: bindings.runtime.ResourceHandle = bindings.runtime.ResourceHandle(0)
    internal constructor(handle: bindings.runtime.ResourceHandle) { __handle = handle }
    override fun close() { __cm_resource_abi_import_Layout_ParagraphBuilder_drop(__handle.value) }
    fun setAlign(a: bindings.Layout.Align) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_setAlign(handle, a.ordinal)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun setDirection(d: bindings.Layout.TextDirection) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_setDirection(handle, d.ordinal)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    0 = unlimited.
    */
    fun setMaxLines(n: kotlin.UInt) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_setMaxLines(handle, n.toInt())
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun setEllipsis(e: kotlin.String) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;

        val bytearray = e.encodeToByteArray()
        val len = bytearray.size
        val ptr = allocator.writeToLinearMemory(bytearray).address.toInt()

        __wasm_import_setEllipsis(handle, ptr, len)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun pushStyle(style: bindings.Layout.TextStyle) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(56+5*4), align=4)*/ allocator.allocate((56+5*4)).address.toInt()
        var handle = this.__handle.value;
        (ptr + 0).ptr.storeInt(handle)

        val bytearray = style.family.encodeToByteArray()
        val len = bytearray.size
        val ptr0 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (2*4)).ptr.storeInt(len)
        (ptr + 4).ptr.storeInt(ptr0)
        (ptr + (3*4)).ptr.storeFloat(style.size)
        (ptr + (4+3*4)).ptr.storeInt(style.weight.toInt())
        (ptr + (8+3*4)).ptr.storeByte((if(style.italic) 1 else 0).toByte())
        (ptr + (12+3*4)).ptr.storeInt(style.color.toInt())
        (ptr + (16+3*4)).ptr.storeFloat(style.letterSpacing)
        (ptr + (20+3*4)).ptr.storeFloat(style.lineHeight)
        (ptr + (24+3*4)).ptr.storeFloat(style.baselineShift)
        val payload1 = style.decoration
        if (payload1 != null) {
          (ptr + (28+3*4)).ptr.storeByte(1.toByte())
          (ptr + (32+3*4)).ptr.storeByte((if(payload1.underline) 1 else 0).toByte())
          (ptr + (33+3*4)).ptr.storeByte((if(payload1.overline) 1 else 0).toByte())
          (ptr + (34+3*4)).ptr.storeByte((if(payload1.lineThrough) 1 else 0).toByte())
          (ptr + (36+3*4)).ptr.storeInt(payload1.color.toInt())
          (ptr + (40+3*4)).ptr.storeByte(payload1.style.ordinal.toByte())
          (ptr + (44+3*4)).ptr.storeFloat(payload1.thickness)
        } else {
          (ptr + (28+3*4)).ptr.storeByte(0.toByte())
        }

        val address = allocator.allocate(style.shadows.size * 16 /*, align_wasm32=4*/).address.toInt()
        for ((index, el) in style.shadows.withIndex()) {
          val base = address + (index * 16)
          (base + 0).ptr.storeInt(el.color.toInt())
          (base + 4).ptr.storeFloat(el.offset.x)
          (base + 8).ptr.storeFloat(el.offset.y)
          (base + 12).ptr.storeFloat(el.sigma)

        }
        (ptr + (48+4*4)).ptr.storeInt(style.shadows.size)
        (ptr + (48+3*4)).ptr.storeInt(address)
        val payload3 = style.background
        if (payload3 != null) {
          (ptr + (48+5*4)).ptr.storeByte(1.toByte())
          (ptr + (52+5*4)).ptr.storeInt(payload3.toInt())
        } else {
          (ptr + (48+5*4)).ptr.storeByte(0.toByte())
        }
        __wasm_import_pushStyle(ptr)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun popStyle() {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_popStyle(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun addText(text: kotlin.String) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;

        val bytearray = text.encodeToByteArray()
        val len = bytearray.size
        val ptr = allocator.writeToLinearMemory(bytearray).address.toInt()

        __wasm_import_addText(handle, ptr, len)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    companion object {
      fun new(defaultStyle: bindings.Layout.TextStyle): bindings.Layout.ParagraphBuilder {
        // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
        kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
          val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(56+4*4), align=4)*/ allocator.allocate((56+4*4)).address.toInt()

          val bytearray = defaultStyle.family.encodeToByteArray()
          val len = bytearray.size
          val ptr0 = allocator.writeToLinearMemory(bytearray).address.toInt()

          (ptr + 4).ptr.storeInt(len)
          (ptr + 0).ptr.storeInt(ptr0)
          (ptr + (2*4)).ptr.storeFloat(defaultStyle.size)
          (ptr + (4+2*4)).ptr.storeInt(defaultStyle.weight.toInt())
          (ptr + (8+2*4)).ptr.storeByte((if(defaultStyle.italic) 1 else 0).toByte())
          (ptr + (12+2*4)).ptr.storeInt(defaultStyle.color.toInt())
          (ptr + (16+2*4)).ptr.storeFloat(defaultStyle.letterSpacing)
          (ptr + (20+2*4)).ptr.storeFloat(defaultStyle.lineHeight)
          (ptr + (24+2*4)).ptr.storeFloat(defaultStyle.baselineShift)
          val payload1 = defaultStyle.decoration
          if (payload1 != null) {
            (ptr + (28+2*4)).ptr.storeByte(1.toByte())
            (ptr + (32+2*4)).ptr.storeByte((if(payload1.underline) 1 else 0).toByte())
            (ptr + (33+2*4)).ptr.storeByte((if(payload1.overline) 1 else 0).toByte())
            (ptr + (34+2*4)).ptr.storeByte((if(payload1.lineThrough) 1 else 0).toByte())
            (ptr + (36+2*4)).ptr.storeInt(payload1.color.toInt())
            (ptr + (40+2*4)).ptr.storeByte(payload1.style.ordinal.toByte())
            (ptr + (44+2*4)).ptr.storeFloat(payload1.thickness)
          } else {
            (ptr + (28+2*4)).ptr.storeByte(0.toByte())
          }

          val address = allocator.allocate(defaultStyle.shadows.size * 16 /*, align_wasm32=4*/).address.toInt()
          for ((index, el) in defaultStyle.shadows.withIndex()) {
            val base = address + (index * 16)
            (base + 0).ptr.storeInt(el.color.toInt())
            (base + 4).ptr.storeFloat(el.offset.x)
            (base + 8).ptr.storeFloat(el.offset.y)
            (base + 12).ptr.storeFloat(el.sigma)

          }
          (ptr + (48+3*4)).ptr.storeInt(defaultStyle.shadows.size)
          (ptr + (48+2*4)).ptr.storeInt(address)
          val payload3 = defaultStyle.background
          if (payload3 != null) {
            (ptr + (48+4*4)).ptr.storeByte(1.toByte())
            (ptr + (52+4*4)).ptr.storeInt(payload3.toInt())
          } else {
            (ptr + (48+4*4)).ptr.storeByte(0.toByte())
          }
          val ret: kotlin.Int = __wasm_import_new(ptr)
          kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
          val resource = bindings.Layout.ParagraphBuilder(bindings.runtime.ResourceHandle(ret))
          return resource
        }
        // </editor-fold>
      }
      /**
      Consumes the builder.
      */
      fun build(b: bindings.Layout.ParagraphBuilder): bindings.Layout.Paragraph {
        // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
        kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
          var handle = b.__handle.value;
          b.__handle = bindings.runtime.ResourceHandle(0);
          val ret: kotlin.Int = __wasm_import_build(handle)
          kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
          val resource = bindings.Layout.Paragraph(bindings.runtime.ResourceHandle(ret))
          return resource
        }
        // </editor-fold>
      }
    }
  }

  // END OF TYPES


}

@WitInterface("wasi:canvas/scene@0.0.2")
/*external */interface Scene {
  @WitImport
  companion object Import : bindings.Scene {
    // <editor-fold defaultstate="collapsed" desc="Generated Import Code">
    /**
    Draw the layer's current content with its current properties.
    On a RECORDING canvas the recording retains the layer HOST-side
    (never the guest's borrow): replay resolves picture + properties
    at replay time; property/content updates never invalidate
    capturing recordings; dropping the guest's handle does not
    invalidate captures (host keeps the layer alive until the last
    capturing recording drops).
    */
    override fun drawLayer(canvas: bindings.Draw.Canvas, l: bindings.Scene.Layer) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = canvas.__handle.value;
        var handle0 = l.__handle.value;
        __wasm_import_drawLayer(handle, handle0)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    // </editor-fold>
  }
  // START OF TYPES

  class Layer : kotlin.AutoCloseable {
    internal var __handle: bindings.runtime.ResourceHandle = bindings.runtime.ResourceHandle(0)
    internal constructor(handle: bindings.runtime.ResourceHandle) { __handle = handle }
    override fun close() { __cm_resource_abi_import_Scene_Layer_drop(__handle.value) }
    /**
    Set the layer's content by CONSUMING a recording canvas
    (from graphics.start-recording). The recording is finished
    as LIVE content: layers drawn into it via draw-layer stay
    resolved at replay time, so nested layers keep working when
    a parent re-records (snapshot-into-picture would freeze
    them — why this is not `set-picture`, which is also R5-
    derivable from this). Traps if `recording` is not a
    recording canvas.
    */
    fun setContent(recording: bindings.Draw.Canvas) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        var handle0 = recording.__handle.value;
        recording.__handle = bindings.runtime.ResourceHandle(0);
        __wasm_import_setContent(handle, handle0)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun setBounds(bounds: bindings.Types.Rect) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_setBounds(handle, bounds.x, bounds.y, bounds.width, bounds.height)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun setTransform(t: bindings.Types.Transform) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_setTransform(handle, t.m00, t.m01, t.m02, t.m10, t.m11, t.m12, t.m20, t.m21, t.m22)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    0..255 alpha applied at replay.
    */
    fun setAlpha(alpha: kotlin.UByte) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_setAlpha(handle, alpha.toInt())
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun setClipRect(r: bindings.Types.Rect, antiAlias: kotlin.Boolean) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_setClipRect(handle, r.x, r.y, r.width, r.height, (if(antiAlias) 1 else 0))
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun setClipRoundedRect(rr: bindings.Types.RoundedRect, antiAlias: kotlin.Boolean) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_setClipRoundedRect(handle, rr.rect.x, rr.rect.y, rr.rect.width, rr.rect.height, rr.topLeft.x, rr.topLeft.y, rr.topRight.x, rr.topRight.y, rr.bottomRight.x, rr.bottomRight.y, rr.bottomLeft.x, rr.bottomLeft.y, (if(antiAlias) 1 else 0))
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    SVG path data (Flutter ClipPathLayer; Compose outline clips).
    */
    fun setClipPath(path: kotlin.String, antiAlias: kotlin.Boolean) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;

        val bytearray = path.encodeToByteArray()
        val len = bytearray.size
        val ptr = allocator.writeToLinearMemory(bytearray).address.toInt()

        __wasm_import_setClipPath(handle, ptr, len, (if(antiAlias) 1 else 0))
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    fun clearClip() {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_clearClip(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    /**
    Material-style drop shadow from the layer's clip outline;
    0 = none.
    */
    fun setShadowElevation(elevation: kotlin.Float) {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_setShadowElevation(handle, elevation)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    companion object {
      /**
      Created through the embedder-granted factory (capability
      rule: host-resident allocation flows through a handle).
      */
      fun new(g: bindings.Draw.Graphics): bindings.Scene.Layer {
        // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
        kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
          var handle = g.__handle.value;
          val ret: kotlin.Int = __wasm_import_new3(handle)
          kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
          val resource = bindings.Scene.Layer(bindings.runtime.ResourceHandle(ret))
          return resource
        }
        // </editor-fold>
      }
    }
  }

  // END OF TYPES

  /**
  Draw the layer's current content with its current properties.
  On a RECORDING canvas the recording retains the layer HOST-side
  (never the guest's borrow): replay resolves picture + properties
  at replay time; property/content updates never invalidate
  capturing recordings; dropping the guest's handle does not
  invalidate captures (host keeps the layer alive until the last
  capturing recording drops).
  */
  fun drawLayer(canvas: bindings.Draw.Canvas, l: bindings.Scene.Layer)

}

@WitInterface("wasi:canvas/embedding@0.0.2")
/*external */interface Embedding {
  @WitImport
  companion object Import : bindings.Embedding {
    // <editor-fold defaultstate="collapsed" desc="Generated Import Code">
    /**
    The context for the guest's (host-assigned) surface. Reactor
    guests have exactly one; under wasi:surface this would instead
    come from `surface.connect-graphics-context`.
    */
    override fun getContext(): bindings.Embedding.CanvasContext {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        val ret: kotlin.Int = __wasm_import_getContext()
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val resource = bindings.Embedding.CanvasContext(bindings.runtime.ResourceHandle(ret))
        return resource
      }
      // </editor-fold>
    }
    // </editor-fold>
  }
  // START OF TYPES

  /**
  The canvas-flavored graphics context for one surface.
  */
  class CanvasContext : kotlin.AutoCloseable {
    internal var __handle: bindings.runtime.ResourceHandle = bindings.runtime.ResourceHandle(0)
    internal constructor(handle: bindings.runtime.ResourceHandle) { __handle = handle }
    override fun close() { __cm_resource_abi_import_Embedding_CanvasContext_drop(__handle.value) }
    /**
    The creation factory (shaders/images/typefaces/pictures…).
    Stable across frames — acquire once.
    */
    fun graphics(): bindings.Draw.Graphics {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Int = __wasm_import_graphics(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val resource = bindings.Draw.Graphics(bindings.runtime.ResourceHandle(ret))
        return resource
      }
      // </editor-fold>
    }
    /**
    Acquire the current frame's buffer: the presented target,
    already cleared/transformed per the embedder's policy. The
    handle is valid until present; the guest should drop it
    before (or it is invalidated at) present.
    */
    fun getCurrentBuffer(): bindings.Draw.Canvas {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        val ret: kotlin.Int = __wasm_import_getCurrentBuffer(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
        val resource = bindings.Draw.Canvas(bindings.runtime.ResourceHandle(ret))
        return resource
      }
      // </editor-fold>
    }
    /**
    Flush + present the buffer acquired by get-current-buffer.
    */
    fun present() {
      // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
      kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
        var handle = this.__handle.value;
        __wasm_import_present(handle)
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      }
      // </editor-fold>
    }
    companion object {
    }
  }

  // END OF TYPES

  /**
  The context for the guest's (host-assigned) surface. Reactor
  guests have exactly one; under wasi:surface this would instead
  come from `surface.connect-graphics-context`.
  */
  fun getContext(): bindings.Embedding.CanvasContext

}

@WitInterface("my:skiko-gfx/renderer@0.1.0")
/*external */interface Renderer {
  // START OF TYPES


  enum class PointerKind {
    DOWN,
    UP,
    MOVE,
    SCROLL,
  }

  enum class KeyKind {
    DOWN,
    UP,
  }

  // END OF TYPES

  fun renderFrame(nanos: kotlin.ULong)
  fun onPointerEvent(kind: bindings.Renderer.PointerKind, x: kotlin.Float, y: kotlin.Float)
  fun onKeyEvent(kind: bindings.Renderer.KeyKind, keyCode: kotlin.UInt)
  fun onResize(w: kotlin.UInt, h: kotlin.UInt)
  /**
  Fired by the host when a previously scheduled callback comes due.
  callback-id is whatever the guest passed to schedule-delayed.
  */
  fun onScheduledCallback(callbackId: kotlin.UInt)
  /**
  Enriched pointer event — same semantics as on-pointer-event plus
  multi-touch pointer-id (0..N) and normalized pressure (0.0..1.0,
  0.0 if the device doesn't report it). Hosts emit both v1 and v2
  for every touch; guests can ignore whichever they don't need.
  */
  fun onPointerEventV2(pointerId: kotlin.UInt, kind: bindings.Renderer.PointerKind, x: kotlin.Float, y: kotlin.Float, pressure: kotlin.Float)
  /**
  Enriched key event — same semantics as on-key-event plus the
  resolved UTF-32 code-point (for printable chars; 0 if not
  printable) and a `key-id` whose numeric value matches Compose's
  webMain `Key(keyCode: Long)` constants (8=Backspace, 9=Tab,
  13=Enter, 37=ArrowLeft, 38=ArrowUp, 39=ArrowRight, 40=ArrowDown,
  46=Delete, 27=Escape, 0=Unknown). For printable text the guest
  should use `code-point` to build a Compose `KeyEvent`; for
  special keys (backspace, arrows, enter) the guest uses `key-id`.
  */
  fun onKeyEventV2(kind: bindings.Renderer.KeyKind, codePoint: kotlin.UInt, keyId: kotlin.UInt)
  /**
  Lifecycle state transition. Fired by the host on every observed
  transition (initial Resumed when the activity comes up, Stopped
  when it's backgrounded, Destroyed on exit).
  */
  fun onLifecycleChanged(state: kotlin.UInt)

}

@WitInterface("wasi:input-handlers/pointer-handler@0.0.2")
/*external */interface PointerHandler {
  // START OF TYPES


  enum class Kind {
    DOWN,
    UP,
    MOVE,
    SCROLL,
    CANCEL,
    ENTER,
    LEAVE,
  }

  enum class PointerDevice {
    UNKNOWN,
    MOUSE,
    TOUCH,
    PEN,
  }

  /**
  The button that CHANGED (down/up); none for move/scroll.
  */
  enum class Button {
    NONE,
    PRIMARY,
    SECONDARY,
    MIDDLE,
    BACK,
    FORWARD,
  }

  /**
  Buttons currently held.
  */
  value class Buttons internal constructor(val _value: kotlin.Long) {
    constructor(
    primary: kotlin.Boolean = false,secondary: kotlin.Boolean = false,middle: kotlin.Boolean = false,back: kotlin.Boolean = false,forward: kotlin.Boolean = false,
    ) : this(0L or (if (primary) (1L shl 0) else 0L) or (if (secondary) (1L shl 1) else 0L) or (if (middle) (1L shl 2) else 0L) or (if (back) (1L shl 3) else 0L) or (if (forward) (1L shl 4) else 0L))
    val primary: kotlin.Boolean get() = (_value and (1L shl 0)) != 0L
    val secondary: kotlin.Boolean get() = (_value and (1L shl 1)) != 0L
    val middle: kotlin.Boolean get() = (_value and (1L shl 2)) != 0L
    val back: kotlin.Boolean get() = (_value and (1L shl 3)) != 0L
    val forward: kotlin.Boolean get() = (_value and (1L shl 4)) != 0L
  }

  class PointerEvent(
    var id: kotlin.UInt,
    var kind: bindings.PointerHandler.Kind,
    var device: bindings.PointerHandler.PointerDevice,
    var x: kotlin.Float,
    var y: kotlin.Float,
    /**
    0.0..1.0; 0.0 when the device doesn't report pressure.
    */
    var pressure: kotlin.Float,
    /**
    Pen tilt in degrees; 0 when unreported.
    */
    var tiltX: kotlin.Float,
    var tiltY: kotlin.Float,
    /**
    Pen barrel rotation in degrees; 0 when unreported.
    */
    var twist: kotlin.Float,
    /**
    Scroll deltas (kind == scroll only; surface units).
    */
    var scrollDx: kotlin.Float,
    var scrollDy: kotlin.Float,
    var button: bindings.PointerHandler.Button,
    var buttons: bindings.PointerHandler.Buttons,
    var alt: kotlin.Boolean,
    var ctrl: kotlin.Boolean,
    var meta: kotlin.Boolean,
    var shift: kotlin.Boolean,
  )

  // END OF TYPES

  fun onPointer(ev: bindings.PointerHandler.PointerEvent)

}

