// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#include "swift_spike.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `wandr:swift-spike/host`

__attribute__((__import_module__("wandr:swift-spike/host"), __import_name__("log")))
extern void __wasm_import_wandr_swift_spike_host_log(uint8_t *, size_t);

__attribute__((__import_module__("wandr:swift-spike/host"), __import_name__("draw-rect")))
extern void __wasm_import_wandr_swift_spike_host_draw_rect(float, float, float, float, int32_t);

// Exported Functions from `swift-spike`


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void swift_spike_string_set(swift_spike_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void swift_spike_string_dup(swift_spike_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void swift_spike_string_dup_n(swift_spike_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void swift_spike_string_free(swift_spike_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void wandr_swift_spike_host_log(swift_spike_string_t *msg) {
  __wasm_import_wandr_swift_spike_host_log((uint8_t *) (*msg).ptr, (*msg).len);
}

void wandr_swift_spike_host_draw_rect(float x, float y, float w, float h, uint32_t argb) {
  __wasm_import_wandr_swift_spike_host_draw_rect(x, y, w, h, (int32_t) (argb));
}

__attribute__((__export_name__("run")))
void __wasm_export_exports_swift_spike_run(void) {
  exports_swift_spike_run();
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_swift_spike(void);
__attribute__((used))
void __component_type_object_force_link_swift_spike_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_swift_spike();
}
