// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#include "swift_spike.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `wasi:canvas/types@0.0.2`

__attribute__((__import_module__("wasi:canvas/types@0.0.2"), __import_name__("[method]image.width")))
extern int32_t __wasm_import_wasi_canvas_types_method_image_width(int32_t);

__attribute__((__import_module__("wasi:canvas/types@0.0.2"), __import_name__("[method]image.height")))
extern int32_t __wasm_import_wasi_canvas_types_method_image_height(int32_t);

// Imported Functions from `wasi:canvas/draw@0.0.2`

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]graphics.linear-gradient")))
extern int32_t __wasm_import_wasi_canvas_draw_method_graphics_linear_gradient(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]graphics.radial-gradient")))
extern int32_t __wasm_import_wasi_canvas_draw_method_graphics_radial_gradient(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]graphics.sweep-gradient")))
extern int32_t __wasm_import_wasi_canvas_draw_method_graphics_sweep_gradient(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]graphics.shader-blend")))
extern int32_t __wasm_import_wasi_canvas_draw_method_graphics_shader_blend(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]graphics.image-pattern")))
extern int32_t __wasm_import_wasi_canvas_draw_method_graphics_image_pattern(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, float, float, float, float, float, float, float, float, float);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]graphics.decode-image")))
extern void __wasm_import_wasi_canvas_draw_method_graphics_decode_image(int32_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]graphics.image-from-rgba8")))
extern void __wasm_import_wasi_canvas_draw_method_graphics_image_from_rgba8(int32_t, int32_t, int32_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]graphics.new-offscreen")))
extern int32_t __wasm_import_wasi_canvas_draw_method_graphics_new_offscreen(int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]graphics.start-recording")))
extern int32_t __wasm_import_wasi_canvas_draw_method_graphics_start_recording(int32_t, float, float, float, float);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]graphics.combine-paths")))
extern void __wasm_import_wasi_canvas_draw_method_graphics_combine_paths(int32_t, uint8_t *, size_t, uint8_t *, size_t, int32_t, uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.width")))
extern float __wasm_import_wasi_canvas_draw_method_canvas_width(int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.height")))
extern float __wasm_import_wasi_canvas_draw_method_canvas_height(int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.save")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_save(int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.save-layer")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_save_layer(int32_t, int32_t, float, float, float, float, int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.restore")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_restore(int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.translate")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_translate(int32_t, float, float);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.scale")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_scale(int32_t, float, float);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.rotate")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_rotate(int32_t, float);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.concat")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_concat(int32_t, float, float, float, float, float, float, float, float, float);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.clip-rect")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_clip_rect(int32_t, float, float, float, float, int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.clip-rounded-rect")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_clip_rounded_rect(int32_t, float, float, float, float, float, float, float, float, float, float, float, float, int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.clip-path")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_clip_path(int32_t, uint8_t *, size_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.clear")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_clear(int32_t, int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.draw-paint")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_draw_paint(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.draw-rect")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_draw_rect(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.draw-rounded-rect")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_draw_rounded_rect(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.draw-double-rounded-rect")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_draw_double_rounded_rect(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.draw-oval")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_draw_oval(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.draw-line")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_draw_line(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.draw-arc")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_draw_arc(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.draw-path")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_draw_path(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.draw-image")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_draw_image(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.draw-image-rect")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_draw_image_rect(uint8_t *);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[static]canvas.finish-recording")))
extern int32_t __wasm_import_wasi_canvas_draw_static_canvas_finish_recording(int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.draw-picture")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_draw_picture(int32_t, int32_t);

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[method]canvas.snapshot")))
extern void __wasm_import_wasi_canvas_draw_method_canvas_snapshot(int32_t, uint8_t *);

// Imported Functions from `wasi:canvas/embedding@0.0.2`

__attribute__((__import_module__("wasi:canvas/embedding@0.0.2"), __import_name__("[method]canvas-context.graphics")))
extern int32_t __wasm_import_wasi_canvas_embedding_method_canvas_context_graphics(int32_t);

__attribute__((__import_module__("wasi:canvas/embedding@0.0.2"), __import_name__("[method]canvas-context.get-current-buffer")))
extern int32_t __wasm_import_wasi_canvas_embedding_method_canvas_context_get_current_buffer(int32_t);

__attribute__((__import_module__("wasi:canvas/embedding@0.0.2"), __import_name__("[method]canvas-context.present")))
extern void __wasm_import_wasi_canvas_embedding_method_canvas_context_present(int32_t);

__attribute__((__import_module__("wasi:canvas/embedding@0.0.2"), __import_name__("get-context")))
extern int32_t __wasm_import_wasi_canvas_embedding_get_context(void);

// Exported Functions from `wasi:input-handlers/frame-handler@0.0.2`



// Exported Functions from `wasi:input-handlers/pointer-handler@0.0.2`


// Exported Functions from `wandr:ui-shell/frame-pacing@0.1.0`


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

__attribute__((__import_module__("wasi:canvas/types@0.0.2"), __import_name__("[resource-drop]shader")))
extern void __wasm_import_wasi_canvas_types_shader_drop(int32_t handle);

void wasi_canvas_types_shader_drop_own(wasi_canvas_types_own_shader_t handle) {
  __wasm_import_wasi_canvas_types_shader_drop(handle.__handle);
}

void wasi_canvas_types_shader_drop_borrow(wasi_canvas_types_borrow_shader_t handle) {
  __wasm_import_wasi_canvas_types_shader_drop(handle.__handle);
}

wasi_canvas_types_borrow_shader_t wasi_canvas_types_borrow_shader(wasi_canvas_types_own_shader_t arg) {
  return (wasi_canvas_types_borrow_shader_t) { arg.__handle };
}

__attribute__((__import_module__("wasi:canvas/types@0.0.2"), __import_name__("[resource-drop]image")))
extern void __wasm_import_wasi_canvas_types_image_drop(int32_t handle);

void wasi_canvas_types_image_drop_own(wasi_canvas_types_own_image_t handle) {
  __wasm_import_wasi_canvas_types_image_drop(handle.__handle);
}

void wasi_canvas_types_image_drop_borrow(wasi_canvas_types_borrow_image_t handle) {
  __wasm_import_wasi_canvas_types_image_drop(handle.__handle);
}

wasi_canvas_types_borrow_image_t wasi_canvas_types_borrow_image(wasi_canvas_types_own_image_t arg) {
  return (wasi_canvas_types_borrow_image_t) { arg.__handle };
}

void wasi_canvas_types_color_filter_free(wasi_canvas_types_color_filter_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      break;
    }
  }
}

void wasi_canvas_types_option_borrow_shader_free(wasi_canvas_types_option_borrow_shader_t *ptr) {
  if (ptr->is_some) {
  }
}

void wasi_canvas_types_option_mask_blur_free(wasi_canvas_types_option_mask_blur_t *ptr) {
  if (ptr->is_some) {
  }
}

void wasi_canvas_types_option_color_filter_free(wasi_canvas_types_option_color_filter_t *ptr) {
  if (ptr->is_some) {
    wasi_canvas_types_color_filter_free(&ptr->val);
  }
}

void wasi_canvas_types_paint_free(wasi_canvas_types_paint_t *ptr) {
  wasi_canvas_types_option_borrow_shader_free(&ptr->shader);
  wasi_canvas_types_option_mask_blur_free(&ptr->blur);
  wasi_canvas_types_option_color_filter_free(&ptr->filter);
}

void wasi_canvas_draw_paint_free(wasi_canvas_draw_paint_t *ptr) {
  wasi_canvas_types_paint_free(ptr);
}

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[resource-drop]picture")))
extern void __wasm_import_wasi_canvas_draw_picture_drop(int32_t handle);

void wasi_canvas_draw_picture_drop_own(wasi_canvas_draw_own_picture_t handle) {
  __wasm_import_wasi_canvas_draw_picture_drop(handle.__handle);
}

void wasi_canvas_draw_picture_drop_borrow(wasi_canvas_draw_borrow_picture_t handle) {
  __wasm_import_wasi_canvas_draw_picture_drop(handle.__handle);
}

wasi_canvas_draw_borrow_picture_t wasi_canvas_draw_borrow_picture(wasi_canvas_draw_own_picture_t arg) {
  return (wasi_canvas_draw_borrow_picture_t) { arg.__handle };
}

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[resource-drop]graphics")))
extern void __wasm_import_wasi_canvas_draw_graphics_drop(int32_t handle);

void wasi_canvas_draw_graphics_drop_own(wasi_canvas_draw_own_graphics_t handle) {
  __wasm_import_wasi_canvas_draw_graphics_drop(handle.__handle);
}

void wasi_canvas_draw_graphics_drop_borrow(wasi_canvas_draw_borrow_graphics_t handle) {
  __wasm_import_wasi_canvas_draw_graphics_drop(handle.__handle);
}

wasi_canvas_draw_borrow_graphics_t wasi_canvas_draw_borrow_graphics(wasi_canvas_draw_own_graphics_t arg) {
  return (wasi_canvas_draw_borrow_graphics_t) { arg.__handle };
}

__attribute__((__import_module__("wasi:canvas/draw@0.0.2"), __import_name__("[resource-drop]canvas")))
extern void __wasm_import_wasi_canvas_draw_canvas_drop(int32_t handle);

void wasi_canvas_draw_canvas_drop_own(wasi_canvas_draw_own_canvas_t handle) {
  __wasm_import_wasi_canvas_draw_canvas_drop(handle.__handle);
}

void wasi_canvas_draw_canvas_drop_borrow(wasi_canvas_draw_borrow_canvas_t handle) {
  __wasm_import_wasi_canvas_draw_canvas_drop(handle.__handle);
}

wasi_canvas_draw_borrow_canvas_t wasi_canvas_draw_borrow_canvas(wasi_canvas_draw_own_canvas_t arg) {
  return (wasi_canvas_draw_borrow_canvas_t) { arg.__handle };
}

void swift_spike_list_tuple2_f32_color_free(swift_spike_list_tuple2_f32_color_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    swift_spike_tuple2_f32_color_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void wasi_canvas_draw_option_transform_free(wasi_canvas_draw_option_transform_t *ptr) {
  if (ptr->is_some) {
  }
}

void swift_spike_list_u8_free(swift_spike_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void wasi_canvas_draw_result_own_image_void_free(wasi_canvas_draw_result_own_image_void_t *ptr) {
  if (!ptr->is_err) {
  }
}

void swift_spike_option_string_free(swift_spike_option_string_t *ptr) {
  if (ptr->is_some) {
    swift_spike_string_free(&ptr->val);
  }
}

void wasi_canvas_draw_option_rect_free(wasi_canvas_draw_option_rect_t *ptr) {
  if (ptr->is_some) {
  }
}

__attribute__((__import_module__("wasi:canvas/embedding@0.0.2"), __import_name__("[resource-drop]canvas-context")))
extern void __wasm_import_wasi_canvas_embedding_canvas_context_drop(int32_t handle);

void wasi_canvas_embedding_canvas_context_drop_own(wasi_canvas_embedding_own_canvas_context_t handle) {
  __wasm_import_wasi_canvas_embedding_canvas_context_drop(handle.__handle);
}

void wasi_canvas_embedding_canvas_context_drop_borrow(wasi_canvas_embedding_borrow_canvas_context_t handle) {
  __wasm_import_wasi_canvas_embedding_canvas_context_drop(handle.__handle);
}

wasi_canvas_embedding_borrow_canvas_context_t wasi_canvas_embedding_borrow_canvas_context(wasi_canvas_embedding_own_canvas_context_t arg) {
  return (wasi_canvas_embedding_borrow_canvas_context_t) { arg.__handle };
}

void swift_spike_string_set(swift_spike_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void swift_spike_string_dup(swift_spike_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void swift_spike_string_dup_n(swift_spike_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void swift_spike_string_free(swift_spike_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

uint32_t wasi_canvas_types_method_image_width(wasi_canvas_types_borrow_image_t self) {
  int32_t ret = __wasm_import_wasi_canvas_types_method_image_width((self).__handle);
  return (uint32_t) (ret);
}

uint32_t wasi_canvas_types_method_image_height(wasi_canvas_types_borrow_image_t self) {
  int32_t ret = __wasm_import_wasi_canvas_types_method_image_height((self).__handle);
  return (uint32_t) (ret);
}

wasi_canvas_draw_own_shader_t wasi_canvas_draw_method_graphics_linear_gradient(wasi_canvas_draw_borrow_graphics_t self, wasi_canvas_draw_point_t *start, wasi_canvas_draw_point_t *end, swift_spike_list_tuple2_f32_color_t *stops, wasi_canvas_draw_tile_mode_t tile, wasi_canvas_draw_transform_t *maybe_local) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(56+4*sizeof(void*))];
  wasi_canvas_draw_option_transform_t local;
  local.is_some = maybe_local != NULL;if (maybe_local) {
    local.val = *maybe_local;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((float*)(ptr + 4)) = (*start).x;
  *((float*)(ptr + 8)) = (*start).y;
  *((float*)(ptr + 12)) = (*end).x;
  *((float*)(ptr + 16)) = (*end).y;
  *((size_t*)(ptr + (16+2*sizeof(void*)))) = (*stops).len;
  *((uint8_t **)(ptr + (16+1*sizeof(void*)))) = (uint8_t *) (*stops).ptr;
  *((int8_t*)(ptr + (16+3*sizeof(void*)))) = (int32_t) tile;
  if ((local).is_some) {
    const wasi_canvas_draw_transform_t *payload0 = &(local).val;
    *((int8_t*)(ptr + (20+3*sizeof(void*)))) = 1;
    *((float*)(ptr + (24+3*sizeof(void*)))) = (*payload0).m00;
    *((float*)(ptr + (28+3*sizeof(void*)))) = (*payload0).m01;
    *((float*)(ptr + (32+3*sizeof(void*)))) = (*payload0).m02;
    *((float*)(ptr + (36+3*sizeof(void*)))) = (*payload0).m10;
    *((float*)(ptr + (40+3*sizeof(void*)))) = (*payload0).m11;
    *((float*)(ptr + (44+3*sizeof(void*)))) = (*payload0).m12;
    *((float*)(ptr + (48+3*sizeof(void*)))) = (*payload0).m20;
    *((float*)(ptr + (52+3*sizeof(void*)))) = (*payload0).m21;
    *((float*)(ptr + (56+3*sizeof(void*)))) = (*payload0).m22;
  } else {
    *((int8_t*)(ptr + (20+3*sizeof(void*)))) = 0;
  }
  int32_t ret = __wasm_import_wasi_canvas_draw_method_graphics_linear_gradient(ptr);
  return (wasi_canvas_draw_own_shader_t) { ret };
}

wasi_canvas_draw_own_shader_t wasi_canvas_draw_method_graphics_radial_gradient(wasi_canvas_draw_borrow_graphics_t self, wasi_canvas_draw_point_t *center, float radius, swift_spike_list_tuple2_f32_color_t *stops, wasi_canvas_draw_tile_mode_t tile, wasi_canvas_draw_transform_t *maybe_local) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(56+3*sizeof(void*))];
  wasi_canvas_draw_option_transform_t local;
  local.is_some = maybe_local != NULL;if (maybe_local) {
    local.val = *maybe_local;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((float*)(ptr + 4)) = (*center).x;
  *((float*)(ptr + 8)) = (*center).y;
  *((float*)(ptr + 12)) = radius;
  *((size_t*)(ptr + (16+1*sizeof(void*)))) = (*stops).len;
  *((uint8_t **)(ptr + 16)) = (uint8_t *) (*stops).ptr;
  *((int8_t*)(ptr + (16+2*sizeof(void*)))) = (int32_t) tile;
  if ((local).is_some) {
    const wasi_canvas_draw_transform_t *payload0 = &(local).val;
    *((int8_t*)(ptr + (20+2*sizeof(void*)))) = 1;
    *((float*)(ptr + (24+2*sizeof(void*)))) = (*payload0).m00;
    *((float*)(ptr + (28+2*sizeof(void*)))) = (*payload0).m01;
    *((float*)(ptr + (32+2*sizeof(void*)))) = (*payload0).m02;
    *((float*)(ptr + (36+2*sizeof(void*)))) = (*payload0).m10;
    *((float*)(ptr + (40+2*sizeof(void*)))) = (*payload0).m11;
    *((float*)(ptr + (44+2*sizeof(void*)))) = (*payload0).m12;
    *((float*)(ptr + (48+2*sizeof(void*)))) = (*payload0).m20;
    *((float*)(ptr + (52+2*sizeof(void*)))) = (*payload0).m21;
    *((float*)(ptr + (56+2*sizeof(void*)))) = (*payload0).m22;
  } else {
    *((int8_t*)(ptr + (20+2*sizeof(void*)))) = 0;
  }
  int32_t ret = __wasm_import_wasi_canvas_draw_method_graphics_radial_gradient(ptr);
  return (wasi_canvas_draw_own_shader_t) { ret };
}

wasi_canvas_draw_own_shader_t wasi_canvas_draw_method_graphics_sweep_gradient(wasi_canvas_draw_borrow_graphics_t self, wasi_canvas_draw_point_t *center, float start_angle, float end_angle, swift_spike_list_tuple2_f32_color_t *stops, wasi_canvas_draw_tile_mode_t tile, wasi_canvas_draw_transform_t *maybe_local) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(56+4*sizeof(void*))];
  wasi_canvas_draw_option_transform_t local;
  local.is_some = maybe_local != NULL;if (maybe_local) {
    local.val = *maybe_local;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((float*)(ptr + 4)) = (*center).x;
  *((float*)(ptr + 8)) = (*center).y;
  *((float*)(ptr + 12)) = start_angle;
  *((float*)(ptr + 16)) = end_angle;
  *((size_t*)(ptr + (16+2*sizeof(void*)))) = (*stops).len;
  *((uint8_t **)(ptr + (16+1*sizeof(void*)))) = (uint8_t *) (*stops).ptr;
  *((int8_t*)(ptr + (16+3*sizeof(void*)))) = (int32_t) tile;
  if ((local).is_some) {
    const wasi_canvas_draw_transform_t *payload0 = &(local).val;
    *((int8_t*)(ptr + (20+3*sizeof(void*)))) = 1;
    *((float*)(ptr + (24+3*sizeof(void*)))) = (*payload0).m00;
    *((float*)(ptr + (28+3*sizeof(void*)))) = (*payload0).m01;
    *((float*)(ptr + (32+3*sizeof(void*)))) = (*payload0).m02;
    *((float*)(ptr + (36+3*sizeof(void*)))) = (*payload0).m10;
    *((float*)(ptr + (40+3*sizeof(void*)))) = (*payload0).m11;
    *((float*)(ptr + (44+3*sizeof(void*)))) = (*payload0).m12;
    *((float*)(ptr + (48+3*sizeof(void*)))) = (*payload0).m20;
    *((float*)(ptr + (52+3*sizeof(void*)))) = (*payload0).m21;
    *((float*)(ptr + (56+3*sizeof(void*)))) = (*payload0).m22;
  } else {
    *((int8_t*)(ptr + (20+3*sizeof(void*)))) = 0;
  }
  int32_t ret = __wasm_import_wasi_canvas_draw_method_graphics_sweep_gradient(ptr);
  return (wasi_canvas_draw_own_shader_t) { ret };
}

wasi_canvas_draw_own_shader_t wasi_canvas_draw_method_graphics_shader_blend(wasi_canvas_draw_borrow_graphics_t self, wasi_canvas_draw_blend_mode_t mode, wasi_canvas_draw_borrow_shader_t dst, wasi_canvas_draw_borrow_shader_t src) {
  int32_t ret = __wasm_import_wasi_canvas_draw_method_graphics_shader_blend((self).__handle, (int32_t) mode, (dst).__handle, (src).__handle);
  return (wasi_canvas_draw_own_shader_t) { ret };
}

wasi_canvas_draw_own_shader_t wasi_canvas_draw_method_graphics_image_pattern(wasi_canvas_draw_borrow_graphics_t self, wasi_canvas_draw_borrow_image_t image, wasi_canvas_draw_tile_mode_t tile_x, wasi_canvas_draw_tile_mode_t tile_y, wasi_canvas_draw_sampling_t *sampling, wasi_canvas_draw_transform_t *local) {
  int32_t ret = __wasm_import_wasi_canvas_draw_method_graphics_image_pattern((self).__handle, (image).__handle, (int32_t) tile_x, (int32_t) tile_y, (int32_t) (*sampling).filter, (int32_t) (*sampling).mipmap, (*local).m00, (*local).m01, (*local).m02, (*local).m10, (*local).m11, (*local).m12, (*local).m20, (*local).m21, (*local).m22);
  return (wasi_canvas_draw_own_shader_t) { ret };
}

bool wasi_canvas_draw_method_graphics_decode_image(wasi_canvas_draw_borrow_graphics_t self, swift_spike_list_u8_t *bytes, wasi_canvas_draw_own_image_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasi_canvas_draw_method_graphics_decode_image((self).__handle, (uint8_t *) (*bytes).ptr, (*bytes).len, ptr);
  wasi_canvas_draw_result_own_image_void_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_canvas_draw_own_image_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

bool wasi_canvas_draw_method_graphics_image_from_rgba8(wasi_canvas_draw_borrow_graphics_t self, uint32_t width, uint32_t height, swift_spike_list_u8_t *pixels, wasi_canvas_draw_own_image_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasi_canvas_draw_method_graphics_image_from_rgba8((self).__handle, (int32_t) (width), (int32_t) (height), (uint8_t *) (*pixels).ptr, (*pixels).len, ptr);
  wasi_canvas_draw_result_own_image_void_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_canvas_draw_own_image_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

wasi_canvas_draw_own_canvas_t wasi_canvas_draw_method_graphics_new_offscreen(wasi_canvas_draw_borrow_graphics_t self, uint32_t width, uint32_t height) {
  int32_t ret = __wasm_import_wasi_canvas_draw_method_graphics_new_offscreen((self).__handle, (int32_t) (width), (int32_t) (height));
  return (wasi_canvas_draw_own_canvas_t) { ret };
}

wasi_canvas_draw_own_canvas_t wasi_canvas_draw_method_graphics_start_recording(wasi_canvas_draw_borrow_graphics_t self, wasi_canvas_draw_rect_t *bounds) {
  int32_t ret = __wasm_import_wasi_canvas_draw_method_graphics_start_recording((self).__handle, (*bounds).x, (*bounds).y, (*bounds).width, (*bounds).height);
  return (wasi_canvas_draw_own_canvas_t) { ret };
}

bool wasi_canvas_draw_method_graphics_combine_paths(wasi_canvas_draw_borrow_graphics_t self, swift_spike_string_t *a, swift_spike_string_t *b, wasi_canvas_draw_path_op_t op, swift_spike_string_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasi_canvas_draw_method_graphics_combine_paths((self).__handle, (uint8_t *) (*a).ptr, (*a).len, (uint8_t *) (*b).ptr, (*b).len, (int32_t) op, ptr);
  swift_spike_option_string_t option;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (swift_spike_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

float wasi_canvas_draw_method_canvas_width(wasi_canvas_draw_borrow_canvas_t self) {
  float ret = __wasm_import_wasi_canvas_draw_method_canvas_width((self).__handle);
  return ret;
}

float wasi_canvas_draw_method_canvas_height(wasi_canvas_draw_borrow_canvas_t self) {
  float ret = __wasm_import_wasi_canvas_draw_method_canvas_height((self).__handle);
  return ret;
}

void wasi_canvas_draw_method_canvas_save(wasi_canvas_draw_borrow_canvas_t self) {
  __wasm_import_wasi_canvas_draw_method_canvas_save((self).__handle);
}

void wasi_canvas_draw_method_canvas_save_layer(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_rect_t *maybe_bounds, uint8_t alpha) {
  wasi_canvas_draw_option_rect_t bounds;
  bounds.is_some = maybe_bounds != NULL;if (maybe_bounds) {
    bounds.val = *maybe_bounds;
  }
  int32_t option;
  float option1;
  float option2;
  float option3;
  float option4;
  if ((bounds).is_some) {
    const wasi_canvas_draw_rect_t *payload0 = &(bounds).val;
    option = 1;
    option1 = (*payload0).x;
    option2 = (*payload0).y;
    option3 = (*payload0).width;
    option4 = (*payload0).height;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
    option3 = 0;
    option4 = 0;
  }
  __wasm_import_wasi_canvas_draw_method_canvas_save_layer((self).__handle, option, option1, option2, option3, option4, (int32_t) (alpha));
}

void wasi_canvas_draw_method_canvas_restore(wasi_canvas_draw_borrow_canvas_t self) {
  __wasm_import_wasi_canvas_draw_method_canvas_restore((self).__handle);
}

void wasi_canvas_draw_method_canvas_translate(wasi_canvas_draw_borrow_canvas_t self, float dx, float dy) {
  __wasm_import_wasi_canvas_draw_method_canvas_translate((self).__handle, dx, dy);
}

void wasi_canvas_draw_method_canvas_scale(wasi_canvas_draw_borrow_canvas_t self, float sx, float sy) {
  __wasm_import_wasi_canvas_draw_method_canvas_scale((self).__handle, sx, sy);
}

void wasi_canvas_draw_method_canvas_rotate(wasi_canvas_draw_borrow_canvas_t self, float degrees) {
  __wasm_import_wasi_canvas_draw_method_canvas_rotate((self).__handle, degrees);
}

void wasi_canvas_draw_method_canvas_concat(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_transform_t *t) {
  __wasm_import_wasi_canvas_draw_method_canvas_concat((self).__handle, (*t).m00, (*t).m01, (*t).m02, (*t).m10, (*t).m11, (*t).m12, (*t).m20, (*t).m21, (*t).m22);
}

void wasi_canvas_draw_method_canvas_clip_rect(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_rect_t *r, bool anti_alias) {
  __wasm_import_wasi_canvas_draw_method_canvas_clip_rect((self).__handle, (*r).x, (*r).y, (*r).width, (*r).height, anti_alias);
}

void wasi_canvas_draw_method_canvas_clip_rounded_rect(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_rounded_rect_t *rr, bool anti_alias) {
  __wasm_import_wasi_canvas_draw_method_canvas_clip_rounded_rect((self).__handle, ((*rr).rect).x, ((*rr).rect).y, ((*rr).rect).width, ((*rr).rect).height, ((*rr).top_left).x, ((*rr).top_left).y, ((*rr).top_right).x, ((*rr).top_right).y, ((*rr).bottom_right).x, ((*rr).bottom_right).y, ((*rr).bottom_left).x, ((*rr).bottom_left).y, anti_alias);
}

void wasi_canvas_draw_method_canvas_clip_path(wasi_canvas_draw_borrow_canvas_t self, swift_spike_string_t *path, wasi_canvas_draw_fill_rule_t rule, bool anti_alias) {
  __wasm_import_wasi_canvas_draw_method_canvas_clip_path((self).__handle, (uint8_t *) (*path).ptr, (*path).len, (int32_t) rule, anti_alias);
}

void wasi_canvas_draw_method_canvas_clear(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_color_t color) {
  __wasm_import_wasi_canvas_draw_method_canvas_clear((self).__handle, (int32_t) (color));
}

void wasi_canvas_draw_method_canvas_draw_paint(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_paint_t *paint) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[64];
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((int8_t*)(ptr + 4)) = (int32_t) (*paint).style;
  *((int32_t*)(ptr + 8)) = (int32_t) ((*paint).color);
  *((int8_t*)(ptr + 12)) = (int32_t) ((*paint).alpha);
  *((int8_t*)(ptr + 13)) = (int32_t) (*paint).blend;
  *((int8_t*)(ptr + 14)) = (*paint).anti_alias;
  if (((*paint).shader).is_some) {
    const wasi_canvas_types_borrow_shader_t *payload0 = &((*paint).shader).val;
    *((int8_t*)(ptr + 16)) = 1;
    *((int32_t*)(ptr + 20)) = (*payload0).__handle;
  } else {
    *((int8_t*)(ptr + 16)) = 0;
  }
  *((float*)(ptr + 24)) = (*paint).stroke_width;
  *((int8_t*)(ptr + 28)) = (int32_t) (*paint).stroke_cap;
  *((int8_t*)(ptr + 29)) = (int32_t) (*paint).stroke_join;
  *((float*)(ptr + 32)) = (*paint).stroke_miter;
  if (((*paint).blur).is_some) {
    const wasi_canvas_types_mask_blur_t *payload2 = &((*paint).blur).val;
    *((int8_t*)(ptr + 36)) = 1;
    *((int8_t*)(ptr + 40)) = (int32_t) (*payload2).style;
    *((float*)(ptr + 44)) = (*payload2).sigma;
  } else {
    *((int8_t*)(ptr + 36)) = 0;
  }
  if (((*paint).filter).is_some) {
    const wasi_canvas_types_color_filter_t *payload4 = &((*paint).filter).val;
    *((int8_t*)(ptr + 48)) = 1;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        const wasi_canvas_types_color_blend_t *payload5 = &(*payload4).val.blend;
        *((int8_t*)(ptr + 52)) = 0;
        *((int32_t*)(ptr + 56)) = (int32_t) ((*payload5).color);
        *((int8_t*)(ptr + 60)) = (int32_t) (*payload5).mode;
        break;
      }
      case 1: {
        *((int8_t*)(ptr + 52)) = 1;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + 48)) = 0;
  }
  __wasm_import_wasi_canvas_draw_method_canvas_draw_paint(ptr);
}

void wasi_canvas_draw_method_canvas_draw_rect(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_rect_t *r, wasi_canvas_draw_paint_t *paint) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[80];
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((float*)(ptr + 4)) = (*r).x;
  *((float*)(ptr + 8)) = (*r).y;
  *((float*)(ptr + 12)) = (*r).width;
  *((float*)(ptr + 16)) = (*r).height;
  *((int8_t*)(ptr + 20)) = (int32_t) (*paint).style;
  *((int32_t*)(ptr + 24)) = (int32_t) ((*paint).color);
  *((int8_t*)(ptr + 28)) = (int32_t) ((*paint).alpha);
  *((int8_t*)(ptr + 29)) = (int32_t) (*paint).blend;
  *((int8_t*)(ptr + 30)) = (*paint).anti_alias;
  if (((*paint).shader).is_some) {
    const wasi_canvas_types_borrow_shader_t *payload0 = &((*paint).shader).val;
    *((int8_t*)(ptr + 32)) = 1;
    *((int32_t*)(ptr + 36)) = (*payload0).__handle;
  } else {
    *((int8_t*)(ptr + 32)) = 0;
  }
  *((float*)(ptr + 40)) = (*paint).stroke_width;
  *((int8_t*)(ptr + 44)) = (int32_t) (*paint).stroke_cap;
  *((int8_t*)(ptr + 45)) = (int32_t) (*paint).stroke_join;
  *((float*)(ptr + 48)) = (*paint).stroke_miter;
  if (((*paint).blur).is_some) {
    const wasi_canvas_types_mask_blur_t *payload2 = &((*paint).blur).val;
    *((int8_t*)(ptr + 52)) = 1;
    *((int8_t*)(ptr + 56)) = (int32_t) (*payload2).style;
    *((float*)(ptr + 60)) = (*payload2).sigma;
  } else {
    *((int8_t*)(ptr + 52)) = 0;
  }
  if (((*paint).filter).is_some) {
    const wasi_canvas_types_color_filter_t *payload4 = &((*paint).filter).val;
    *((int8_t*)(ptr + 64)) = 1;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        const wasi_canvas_types_color_blend_t *payload5 = &(*payload4).val.blend;
        *((int8_t*)(ptr + 68)) = 0;
        *((int32_t*)(ptr + 72)) = (int32_t) ((*payload5).color);
        *((int8_t*)(ptr + 76)) = (int32_t) (*payload5).mode;
        break;
      }
      case 1: {
        *((int8_t*)(ptr + 68)) = 1;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + 64)) = 0;
  }
  __wasm_import_wasi_canvas_draw_method_canvas_draw_rect(ptr);
}

void wasi_canvas_draw_method_canvas_draw_rounded_rect(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_rounded_rect_t *rr, wasi_canvas_draw_paint_t *paint) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[112];
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((float*)(ptr + 4)) = ((*rr).rect).x;
  *((float*)(ptr + 8)) = ((*rr).rect).y;
  *((float*)(ptr + 12)) = ((*rr).rect).width;
  *((float*)(ptr + 16)) = ((*rr).rect).height;
  *((float*)(ptr + 20)) = ((*rr).top_left).x;
  *((float*)(ptr + 24)) = ((*rr).top_left).y;
  *((float*)(ptr + 28)) = ((*rr).top_right).x;
  *((float*)(ptr + 32)) = ((*rr).top_right).y;
  *((float*)(ptr + 36)) = ((*rr).bottom_right).x;
  *((float*)(ptr + 40)) = ((*rr).bottom_right).y;
  *((float*)(ptr + 44)) = ((*rr).bottom_left).x;
  *((float*)(ptr + 48)) = ((*rr).bottom_left).y;
  *((int8_t*)(ptr + 52)) = (int32_t) (*paint).style;
  *((int32_t*)(ptr + 56)) = (int32_t) ((*paint).color);
  *((int8_t*)(ptr + 60)) = (int32_t) ((*paint).alpha);
  *((int8_t*)(ptr + 61)) = (int32_t) (*paint).blend;
  *((int8_t*)(ptr + 62)) = (*paint).anti_alias;
  if (((*paint).shader).is_some) {
    const wasi_canvas_types_borrow_shader_t *payload0 = &((*paint).shader).val;
    *((int8_t*)(ptr + 64)) = 1;
    *((int32_t*)(ptr + 68)) = (*payload0).__handle;
  } else {
    *((int8_t*)(ptr + 64)) = 0;
  }
  *((float*)(ptr + 72)) = (*paint).stroke_width;
  *((int8_t*)(ptr + 76)) = (int32_t) (*paint).stroke_cap;
  *((int8_t*)(ptr + 77)) = (int32_t) (*paint).stroke_join;
  *((float*)(ptr + 80)) = (*paint).stroke_miter;
  if (((*paint).blur).is_some) {
    const wasi_canvas_types_mask_blur_t *payload2 = &((*paint).blur).val;
    *((int8_t*)(ptr + 84)) = 1;
    *((int8_t*)(ptr + 88)) = (int32_t) (*payload2).style;
    *((float*)(ptr + 92)) = (*payload2).sigma;
  } else {
    *((int8_t*)(ptr + 84)) = 0;
  }
  if (((*paint).filter).is_some) {
    const wasi_canvas_types_color_filter_t *payload4 = &((*paint).filter).val;
    *((int8_t*)(ptr + 96)) = 1;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        const wasi_canvas_types_color_blend_t *payload5 = &(*payload4).val.blend;
        *((int8_t*)(ptr + 100)) = 0;
        *((int32_t*)(ptr + 104)) = (int32_t) ((*payload5).color);
        *((int8_t*)(ptr + 108)) = (int32_t) (*payload5).mode;
        break;
      }
      case 1: {
        *((int8_t*)(ptr + 100)) = 1;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + 96)) = 0;
  }
  __wasm_import_wasi_canvas_draw_method_canvas_draw_rounded_rect(ptr);
}

void wasi_canvas_draw_method_canvas_draw_double_rounded_rect(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_rounded_rect_t *outer, wasi_canvas_draw_rounded_rect_t *inner, wasi_canvas_draw_paint_t *paint) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[160];
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((float*)(ptr + 4)) = ((*outer).rect).x;
  *((float*)(ptr + 8)) = ((*outer).rect).y;
  *((float*)(ptr + 12)) = ((*outer).rect).width;
  *((float*)(ptr + 16)) = ((*outer).rect).height;
  *((float*)(ptr + 20)) = ((*outer).top_left).x;
  *((float*)(ptr + 24)) = ((*outer).top_left).y;
  *((float*)(ptr + 28)) = ((*outer).top_right).x;
  *((float*)(ptr + 32)) = ((*outer).top_right).y;
  *((float*)(ptr + 36)) = ((*outer).bottom_right).x;
  *((float*)(ptr + 40)) = ((*outer).bottom_right).y;
  *((float*)(ptr + 44)) = ((*outer).bottom_left).x;
  *((float*)(ptr + 48)) = ((*outer).bottom_left).y;
  *((float*)(ptr + 52)) = ((*inner).rect).x;
  *((float*)(ptr + 56)) = ((*inner).rect).y;
  *((float*)(ptr + 60)) = ((*inner).rect).width;
  *((float*)(ptr + 64)) = ((*inner).rect).height;
  *((float*)(ptr + 68)) = ((*inner).top_left).x;
  *((float*)(ptr + 72)) = ((*inner).top_left).y;
  *((float*)(ptr + 76)) = ((*inner).top_right).x;
  *((float*)(ptr + 80)) = ((*inner).top_right).y;
  *((float*)(ptr + 84)) = ((*inner).bottom_right).x;
  *((float*)(ptr + 88)) = ((*inner).bottom_right).y;
  *((float*)(ptr + 92)) = ((*inner).bottom_left).x;
  *((float*)(ptr + 96)) = ((*inner).bottom_left).y;
  *((int8_t*)(ptr + 100)) = (int32_t) (*paint).style;
  *((int32_t*)(ptr + 104)) = (int32_t) ((*paint).color);
  *((int8_t*)(ptr + 108)) = (int32_t) ((*paint).alpha);
  *((int8_t*)(ptr + 109)) = (int32_t) (*paint).blend;
  *((int8_t*)(ptr + 110)) = (*paint).anti_alias;
  if (((*paint).shader).is_some) {
    const wasi_canvas_types_borrow_shader_t *payload0 = &((*paint).shader).val;
    *((int8_t*)(ptr + 112)) = 1;
    *((int32_t*)(ptr + 116)) = (*payload0).__handle;
  } else {
    *((int8_t*)(ptr + 112)) = 0;
  }
  *((float*)(ptr + 120)) = (*paint).stroke_width;
  *((int8_t*)(ptr + 124)) = (int32_t) (*paint).stroke_cap;
  *((int8_t*)(ptr + 125)) = (int32_t) (*paint).stroke_join;
  *((float*)(ptr + 128)) = (*paint).stroke_miter;
  if (((*paint).blur).is_some) {
    const wasi_canvas_types_mask_blur_t *payload2 = &((*paint).blur).val;
    *((int8_t*)(ptr + 132)) = 1;
    *((int8_t*)(ptr + 136)) = (int32_t) (*payload2).style;
    *((float*)(ptr + 140)) = (*payload2).sigma;
  } else {
    *((int8_t*)(ptr + 132)) = 0;
  }
  if (((*paint).filter).is_some) {
    const wasi_canvas_types_color_filter_t *payload4 = &((*paint).filter).val;
    *((int8_t*)(ptr + 144)) = 1;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        const wasi_canvas_types_color_blend_t *payload5 = &(*payload4).val.blend;
        *((int8_t*)(ptr + 148)) = 0;
        *((int32_t*)(ptr + 152)) = (int32_t) ((*payload5).color);
        *((int8_t*)(ptr + 156)) = (int32_t) (*payload5).mode;
        break;
      }
      case 1: {
        *((int8_t*)(ptr + 148)) = 1;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + 144)) = 0;
  }
  __wasm_import_wasi_canvas_draw_method_canvas_draw_double_rounded_rect(ptr);
}

void wasi_canvas_draw_method_canvas_draw_oval(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_rect_t *bounds, wasi_canvas_draw_paint_t *paint) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[80];
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((float*)(ptr + 4)) = (*bounds).x;
  *((float*)(ptr + 8)) = (*bounds).y;
  *((float*)(ptr + 12)) = (*bounds).width;
  *((float*)(ptr + 16)) = (*bounds).height;
  *((int8_t*)(ptr + 20)) = (int32_t) (*paint).style;
  *((int32_t*)(ptr + 24)) = (int32_t) ((*paint).color);
  *((int8_t*)(ptr + 28)) = (int32_t) ((*paint).alpha);
  *((int8_t*)(ptr + 29)) = (int32_t) (*paint).blend;
  *((int8_t*)(ptr + 30)) = (*paint).anti_alias;
  if (((*paint).shader).is_some) {
    const wasi_canvas_types_borrow_shader_t *payload0 = &((*paint).shader).val;
    *((int8_t*)(ptr + 32)) = 1;
    *((int32_t*)(ptr + 36)) = (*payload0).__handle;
  } else {
    *((int8_t*)(ptr + 32)) = 0;
  }
  *((float*)(ptr + 40)) = (*paint).stroke_width;
  *((int8_t*)(ptr + 44)) = (int32_t) (*paint).stroke_cap;
  *((int8_t*)(ptr + 45)) = (int32_t) (*paint).stroke_join;
  *((float*)(ptr + 48)) = (*paint).stroke_miter;
  if (((*paint).blur).is_some) {
    const wasi_canvas_types_mask_blur_t *payload2 = &((*paint).blur).val;
    *((int8_t*)(ptr + 52)) = 1;
    *((int8_t*)(ptr + 56)) = (int32_t) (*payload2).style;
    *((float*)(ptr + 60)) = (*payload2).sigma;
  } else {
    *((int8_t*)(ptr + 52)) = 0;
  }
  if (((*paint).filter).is_some) {
    const wasi_canvas_types_color_filter_t *payload4 = &((*paint).filter).val;
    *((int8_t*)(ptr + 64)) = 1;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        const wasi_canvas_types_color_blend_t *payload5 = &(*payload4).val.blend;
        *((int8_t*)(ptr + 68)) = 0;
        *((int32_t*)(ptr + 72)) = (int32_t) ((*payload5).color);
        *((int8_t*)(ptr + 76)) = (int32_t) (*payload5).mode;
        break;
      }
      case 1: {
        *((int8_t*)(ptr + 68)) = 1;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + 64)) = 0;
  }
  __wasm_import_wasi_canvas_draw_method_canvas_draw_oval(ptr);
}

void wasi_canvas_draw_method_canvas_draw_line(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_point_t *start, wasi_canvas_draw_point_t *end, wasi_canvas_draw_paint_t *paint) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[80];
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((float*)(ptr + 4)) = (*start).x;
  *((float*)(ptr + 8)) = (*start).y;
  *((float*)(ptr + 12)) = (*end).x;
  *((float*)(ptr + 16)) = (*end).y;
  *((int8_t*)(ptr + 20)) = (int32_t) (*paint).style;
  *((int32_t*)(ptr + 24)) = (int32_t) ((*paint).color);
  *((int8_t*)(ptr + 28)) = (int32_t) ((*paint).alpha);
  *((int8_t*)(ptr + 29)) = (int32_t) (*paint).blend;
  *((int8_t*)(ptr + 30)) = (*paint).anti_alias;
  if (((*paint).shader).is_some) {
    const wasi_canvas_types_borrow_shader_t *payload0 = &((*paint).shader).val;
    *((int8_t*)(ptr + 32)) = 1;
    *((int32_t*)(ptr + 36)) = (*payload0).__handle;
  } else {
    *((int8_t*)(ptr + 32)) = 0;
  }
  *((float*)(ptr + 40)) = (*paint).stroke_width;
  *((int8_t*)(ptr + 44)) = (int32_t) (*paint).stroke_cap;
  *((int8_t*)(ptr + 45)) = (int32_t) (*paint).stroke_join;
  *((float*)(ptr + 48)) = (*paint).stroke_miter;
  if (((*paint).blur).is_some) {
    const wasi_canvas_types_mask_blur_t *payload2 = &((*paint).blur).val;
    *((int8_t*)(ptr + 52)) = 1;
    *((int8_t*)(ptr + 56)) = (int32_t) (*payload2).style;
    *((float*)(ptr + 60)) = (*payload2).sigma;
  } else {
    *((int8_t*)(ptr + 52)) = 0;
  }
  if (((*paint).filter).is_some) {
    const wasi_canvas_types_color_filter_t *payload4 = &((*paint).filter).val;
    *((int8_t*)(ptr + 64)) = 1;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        const wasi_canvas_types_color_blend_t *payload5 = &(*payload4).val.blend;
        *((int8_t*)(ptr + 68)) = 0;
        *((int32_t*)(ptr + 72)) = (int32_t) ((*payload5).color);
        *((int8_t*)(ptr + 76)) = (int32_t) (*payload5).mode;
        break;
      }
      case 1: {
        *((int8_t*)(ptr + 68)) = 1;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + 64)) = 0;
  }
  __wasm_import_wasi_canvas_draw_method_canvas_draw_line(ptr);
}

void wasi_canvas_draw_method_canvas_draw_arc(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_rect_t *bounds, float start_angle, float sweep_angle, bool include_center, wasi_canvas_draw_paint_t *paint) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[92];
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((float*)(ptr + 4)) = (*bounds).x;
  *((float*)(ptr + 8)) = (*bounds).y;
  *((float*)(ptr + 12)) = (*bounds).width;
  *((float*)(ptr + 16)) = (*bounds).height;
  *((float*)(ptr + 20)) = start_angle;
  *((float*)(ptr + 24)) = sweep_angle;
  *((int8_t*)(ptr + 28)) = include_center;
  *((int8_t*)(ptr + 32)) = (int32_t) (*paint).style;
  *((int32_t*)(ptr + 36)) = (int32_t) ((*paint).color);
  *((int8_t*)(ptr + 40)) = (int32_t) ((*paint).alpha);
  *((int8_t*)(ptr + 41)) = (int32_t) (*paint).blend;
  *((int8_t*)(ptr + 42)) = (*paint).anti_alias;
  if (((*paint).shader).is_some) {
    const wasi_canvas_types_borrow_shader_t *payload0 = &((*paint).shader).val;
    *((int8_t*)(ptr + 44)) = 1;
    *((int32_t*)(ptr + 48)) = (*payload0).__handle;
  } else {
    *((int8_t*)(ptr + 44)) = 0;
  }
  *((float*)(ptr + 52)) = (*paint).stroke_width;
  *((int8_t*)(ptr + 56)) = (int32_t) (*paint).stroke_cap;
  *((int8_t*)(ptr + 57)) = (int32_t) (*paint).stroke_join;
  *((float*)(ptr + 60)) = (*paint).stroke_miter;
  if (((*paint).blur).is_some) {
    const wasi_canvas_types_mask_blur_t *payload2 = &((*paint).blur).val;
    *((int8_t*)(ptr + 64)) = 1;
    *((int8_t*)(ptr + 68)) = (int32_t) (*payload2).style;
    *((float*)(ptr + 72)) = (*payload2).sigma;
  } else {
    *((int8_t*)(ptr + 64)) = 0;
  }
  if (((*paint).filter).is_some) {
    const wasi_canvas_types_color_filter_t *payload4 = &((*paint).filter).val;
    *((int8_t*)(ptr + 76)) = 1;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        const wasi_canvas_types_color_blend_t *payload5 = &(*payload4).val.blend;
        *((int8_t*)(ptr + 80)) = 0;
        *((int32_t*)(ptr + 84)) = (int32_t) ((*payload5).color);
        *((int8_t*)(ptr + 88)) = (int32_t) (*payload5).mode;
        break;
      }
      case 1: {
        *((int8_t*)(ptr + 80)) = 1;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + 76)) = 0;
  }
  __wasm_import_wasi_canvas_draw_method_canvas_draw_arc(ptr);
}

void wasi_canvas_draw_method_canvas_draw_path(wasi_canvas_draw_borrow_canvas_t self, swift_spike_string_t *path, wasi_canvas_draw_fill_rule_t rule, wasi_canvas_draw_paint_t *paint) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(64+3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((size_t*)(ptr + (2*sizeof(void*)))) = (*path).len;
  *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*path).ptr;
  *((int8_t*)(ptr + (3*sizeof(void*)))) = (int32_t) rule;
  *((int8_t*)(ptr + (4+3*sizeof(void*)))) = (int32_t) (*paint).style;
  *((int32_t*)(ptr + (8+3*sizeof(void*)))) = (int32_t) ((*paint).color);
  *((int8_t*)(ptr + (12+3*sizeof(void*)))) = (int32_t) ((*paint).alpha);
  *((int8_t*)(ptr + (13+3*sizeof(void*)))) = (int32_t) (*paint).blend;
  *((int8_t*)(ptr + (14+3*sizeof(void*)))) = (*paint).anti_alias;
  if (((*paint).shader).is_some) {
    const wasi_canvas_types_borrow_shader_t *payload0 = &((*paint).shader).val;
    *((int8_t*)(ptr + (16+3*sizeof(void*)))) = 1;
    *((int32_t*)(ptr + (20+3*sizeof(void*)))) = (*payload0).__handle;
  } else {
    *((int8_t*)(ptr + (16+3*sizeof(void*)))) = 0;
  }
  *((float*)(ptr + (24+3*sizeof(void*)))) = (*paint).stroke_width;
  *((int8_t*)(ptr + (28+3*sizeof(void*)))) = (int32_t) (*paint).stroke_cap;
  *((int8_t*)(ptr + (29+3*sizeof(void*)))) = (int32_t) (*paint).stroke_join;
  *((float*)(ptr + (32+3*sizeof(void*)))) = (*paint).stroke_miter;
  if (((*paint).blur).is_some) {
    const wasi_canvas_types_mask_blur_t *payload2 = &((*paint).blur).val;
    *((int8_t*)(ptr + (36+3*sizeof(void*)))) = 1;
    *((int8_t*)(ptr + (40+3*sizeof(void*)))) = (int32_t) (*payload2).style;
    *((float*)(ptr + (44+3*sizeof(void*)))) = (*payload2).sigma;
  } else {
    *((int8_t*)(ptr + (36+3*sizeof(void*)))) = 0;
  }
  if (((*paint).filter).is_some) {
    const wasi_canvas_types_color_filter_t *payload4 = &((*paint).filter).val;
    *((int8_t*)(ptr + (48+3*sizeof(void*)))) = 1;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        const wasi_canvas_types_color_blend_t *payload5 = &(*payload4).val.blend;
        *((int8_t*)(ptr + (52+3*sizeof(void*)))) = 0;
        *((int32_t*)(ptr + (56+3*sizeof(void*)))) = (int32_t) ((*payload5).color);
        *((int8_t*)(ptr + (60+3*sizeof(void*)))) = (int32_t) (*payload5).mode;
        break;
      }
      case 1: {
        *((int8_t*)(ptr + (52+3*sizeof(void*)))) = 1;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + (48+3*sizeof(void*)))) = 0;
  }
  __wasm_import_wasi_canvas_draw_method_canvas_draw_path(ptr);
}

void wasi_canvas_draw_method_canvas_draw_image(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_borrow_image_t image, wasi_canvas_draw_point_t *at, wasi_canvas_draw_sampling_t *sampling, wasi_canvas_draw_paint_t *paint) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[80];
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((int32_t*)(ptr + 4)) = (image).__handle;
  *((float*)(ptr + 8)) = (*at).x;
  *((float*)(ptr + 12)) = (*at).y;
  *((int8_t*)(ptr + 16)) = (int32_t) (*sampling).filter;
  *((int8_t*)(ptr + 17)) = (int32_t) (*sampling).mipmap;
  *((int8_t*)(ptr + 20)) = (int32_t) (*paint).style;
  *((int32_t*)(ptr + 24)) = (int32_t) ((*paint).color);
  *((int8_t*)(ptr + 28)) = (int32_t) ((*paint).alpha);
  *((int8_t*)(ptr + 29)) = (int32_t) (*paint).blend;
  *((int8_t*)(ptr + 30)) = (*paint).anti_alias;
  if (((*paint).shader).is_some) {
    const wasi_canvas_types_borrow_shader_t *payload0 = &((*paint).shader).val;
    *((int8_t*)(ptr + 32)) = 1;
    *((int32_t*)(ptr + 36)) = (*payload0).__handle;
  } else {
    *((int8_t*)(ptr + 32)) = 0;
  }
  *((float*)(ptr + 40)) = (*paint).stroke_width;
  *((int8_t*)(ptr + 44)) = (int32_t) (*paint).stroke_cap;
  *((int8_t*)(ptr + 45)) = (int32_t) (*paint).stroke_join;
  *((float*)(ptr + 48)) = (*paint).stroke_miter;
  if (((*paint).blur).is_some) {
    const wasi_canvas_types_mask_blur_t *payload2 = &((*paint).blur).val;
    *((int8_t*)(ptr + 52)) = 1;
    *((int8_t*)(ptr + 56)) = (int32_t) (*payload2).style;
    *((float*)(ptr + 60)) = (*payload2).sigma;
  } else {
    *((int8_t*)(ptr + 52)) = 0;
  }
  if (((*paint).filter).is_some) {
    const wasi_canvas_types_color_filter_t *payload4 = &((*paint).filter).val;
    *((int8_t*)(ptr + 64)) = 1;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        const wasi_canvas_types_color_blend_t *payload5 = &(*payload4).val.blend;
        *((int8_t*)(ptr + 68)) = 0;
        *((int32_t*)(ptr + 72)) = (int32_t) ((*payload5).color);
        *((int8_t*)(ptr + 76)) = (int32_t) (*payload5).mode;
        break;
      }
      case 1: {
        *((int8_t*)(ptr + 68)) = 1;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + 64)) = 0;
  }
  __wasm_import_wasi_canvas_draw_method_canvas_draw_image(ptr);
}

void wasi_canvas_draw_method_canvas_draw_image_rect(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_borrow_image_t image, wasi_canvas_draw_rect_t *src, wasi_canvas_draw_rect_t *dst, wasi_canvas_draw_sampling_t *sampling, wasi_canvas_draw_paint_t *paint) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[104];
  uint8_t *ptr = (uint8_t *) &ret_area;
  *((int32_t*)(ptr + 0)) = (self).__handle;
  *((int32_t*)(ptr + 4)) = (image).__handle;
  *((float*)(ptr + 8)) = (*src).x;
  *((float*)(ptr + 12)) = (*src).y;
  *((float*)(ptr + 16)) = (*src).width;
  *((float*)(ptr + 20)) = (*src).height;
  *((float*)(ptr + 24)) = (*dst).x;
  *((float*)(ptr + 28)) = (*dst).y;
  *((float*)(ptr + 32)) = (*dst).width;
  *((float*)(ptr + 36)) = (*dst).height;
  *((int8_t*)(ptr + 40)) = (int32_t) (*sampling).filter;
  *((int8_t*)(ptr + 41)) = (int32_t) (*sampling).mipmap;
  *((int8_t*)(ptr + 44)) = (int32_t) (*paint).style;
  *((int32_t*)(ptr + 48)) = (int32_t) ((*paint).color);
  *((int8_t*)(ptr + 52)) = (int32_t) ((*paint).alpha);
  *((int8_t*)(ptr + 53)) = (int32_t) (*paint).blend;
  *((int8_t*)(ptr + 54)) = (*paint).anti_alias;
  if (((*paint).shader).is_some) {
    const wasi_canvas_types_borrow_shader_t *payload0 = &((*paint).shader).val;
    *((int8_t*)(ptr + 56)) = 1;
    *((int32_t*)(ptr + 60)) = (*payload0).__handle;
  } else {
    *((int8_t*)(ptr + 56)) = 0;
  }
  *((float*)(ptr + 64)) = (*paint).stroke_width;
  *((int8_t*)(ptr + 68)) = (int32_t) (*paint).stroke_cap;
  *((int8_t*)(ptr + 69)) = (int32_t) (*paint).stroke_join;
  *((float*)(ptr + 72)) = (*paint).stroke_miter;
  if (((*paint).blur).is_some) {
    const wasi_canvas_types_mask_blur_t *payload2 = &((*paint).blur).val;
    *((int8_t*)(ptr + 76)) = 1;
    *((int8_t*)(ptr + 80)) = (int32_t) (*payload2).style;
    *((float*)(ptr + 84)) = (*payload2).sigma;
  } else {
    *((int8_t*)(ptr + 76)) = 0;
  }
  if (((*paint).filter).is_some) {
    const wasi_canvas_types_color_filter_t *payload4 = &((*paint).filter).val;
    *((int8_t*)(ptr + 88)) = 1;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        const wasi_canvas_types_color_blend_t *payload5 = &(*payload4).val.blend;
        *((int8_t*)(ptr + 92)) = 0;
        *((int32_t*)(ptr + 96)) = (int32_t) ((*payload5).color);
        *((int8_t*)(ptr + 100)) = (int32_t) (*payload5).mode;
        break;
      }
      case 1: {
        *((int8_t*)(ptr + 92)) = 1;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + 88)) = 0;
  }
  __wasm_import_wasi_canvas_draw_method_canvas_draw_image_rect(ptr);
}

wasi_canvas_draw_own_picture_t wasi_canvas_draw_static_canvas_finish_recording(wasi_canvas_draw_own_canvas_t c) {
  int32_t ret = __wasm_import_wasi_canvas_draw_static_canvas_finish_recording((c).__handle);
  return (wasi_canvas_draw_own_picture_t) { ret };
}

void wasi_canvas_draw_method_canvas_draw_picture(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_borrow_picture_t p) {
  __wasm_import_wasi_canvas_draw_method_canvas_draw_picture((self).__handle, (p).__handle);
}

bool wasi_canvas_draw_method_canvas_snapshot(wasi_canvas_draw_borrow_canvas_t self, wasi_canvas_draw_own_image_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasi_canvas_draw_method_canvas_snapshot((self).__handle, ptr);
  wasi_canvas_draw_result_own_image_void_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_canvas_draw_own_image_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

wasi_canvas_embedding_own_graphics_t wasi_canvas_embedding_method_canvas_context_graphics(wasi_canvas_embedding_borrow_canvas_context_t self) {
  int32_t ret = __wasm_import_wasi_canvas_embedding_method_canvas_context_graphics((self).__handle);
  return (wasi_canvas_embedding_own_graphics_t) { ret };
}

wasi_canvas_embedding_own_canvas_t wasi_canvas_embedding_method_canvas_context_get_current_buffer(wasi_canvas_embedding_borrow_canvas_context_t self) {
  int32_t ret = __wasm_import_wasi_canvas_embedding_method_canvas_context_get_current_buffer((self).__handle);
  return (wasi_canvas_embedding_own_canvas_t) { ret };
}

void wasi_canvas_embedding_method_canvas_context_present(wasi_canvas_embedding_borrow_canvas_context_t self) {
  __wasm_import_wasi_canvas_embedding_method_canvas_context_present((self).__handle);
}

wasi_canvas_embedding_own_canvas_context_t wasi_canvas_embedding_get_context(void) {
  int32_t ret = __wasm_import_wasi_canvas_embedding_get_context();
  return (wasi_canvas_embedding_own_canvas_context_t) { ret };
}

__attribute__((__export_name__("wasi:input-handlers/frame-handler@0.0.2#on-frame")))
void __wasm_export_exports_wasi_input_handlers_frame_handler_on_frame(int64_t arg) {
  exports_wasi_input_handlers_frame_handler_on_frame((uint64_t) (arg));
}

__attribute__((__export_name__("wasi:input-handlers/frame-handler@0.0.2#on-resize")))
void __wasm_export_exports_wasi_input_handlers_frame_handler_on_resize(int32_t arg, int32_t arg0) {
  exports_wasi_input_handlers_frame_handler_on_resize((uint32_t) (arg), (uint32_t) (arg0));
}

__attribute__((__export_name__("wasi:input-handlers/pointer-handler@0.0.2#on-pointer")))
void __wasm_export_exports_wasi_input_handlers_pointer_handler_on_pointer(uint8_t * arg) {
  exports_wasi_input_handlers_pointer_handler_pointer_event_t arg0 = (exports_wasi_input_handlers_pointer_handler_pointer_event_t) {
    (uint32_t) (uint32_t) (*((int32_t*) (arg + 0))),
    (exports_wasi_input_handlers_pointer_handler_kind_t) (int32_t) *((uint8_t*) (arg + 4)),
    (exports_wasi_input_handlers_pointer_handler_pointer_device_t) (int32_t) *((uint8_t*) (arg + 5)),
    (float) *((float*) (arg + 8)),
    (float) *((float*) (arg + 12)),
    (float) *((float*) (arg + 16)),
    (float) *((float*) (arg + 20)),
    (float) *((float*) (arg + 24)),
    (float) *((float*) (arg + 28)),
    (float) *((float*) (arg + 32)),
    (float) *((float*) (arg + 36)),
    (exports_wasi_input_handlers_pointer_handler_button_t) (int32_t) *((uint8_t*) (arg + 40)),
    (exports_wasi_input_handlers_pointer_handler_buttons_t) (int32_t) *((uint8_t*) (arg + 41)),
    (bool) (int32_t) *((uint8_t*) (arg + 42)),
    (bool) (int32_t) *((uint8_t*) (arg + 43)),
    (bool) (int32_t) *((uint8_t*) (arg + 44)),
    (bool) (int32_t) *((uint8_t*) (arg + 45)),
  };
  exports_wasi_input_handlers_pointer_handler_on_pointer(&arg0);
  free(arg);
}

__attribute__((__export_name__("wandr:ui-shell/frame-pacing@0.1.0#next-frame-delay")))
int32_t __wasm_export_exports_wandr_ui_shell_frame_pacing_next_frame_delay(void) {
  uint32_t ret = exports_wandr_ui_shell_frame_pacing_next_frame_delay();
  return (int32_t) (ret);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_swift_spike(void);
__attribute__((used))
void __component_type_object_force_link_swift_spike_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_swift_spike();
}
