// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#ifndef __BINDINGS_CWANDR_EXPORTS_H
#define __BINDINGS_CWANDR_EXPORTS_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef uint8_t wandr_ui_shell_lifecycle_state_t;

#define WANDR_UI_SHELL_LIFECYCLE_STATE_INITIALIZED 0
#define WANDR_UI_SHELL_LIFECYCLE_STATE_CREATED 1
#define WANDR_UI_SHELL_LIFECYCLE_STATE_STARTED 2
#define WANDR_UI_SHELL_LIFECYCLE_STATE_RESUMED 3
#define WANDR_UI_SHELL_LIFECYCLE_STATE_PAUSED 4
#define WANDR_UI_SHELL_LIFECYCLE_STATE_STOPPED 5
#define WANDR_UI_SHELL_LIFECYCLE_STATE_DESTROYED 6

typedef wandr_ui_shell_lifecycle_state_t exports_wandr_ui_shell_shell_events_state_t;

typedef uint8_t exports_wasi_input_handlers_pointer_handler_kind_t;

#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_KIND_DOWN 0
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_KIND_UP 1
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_KIND_MOVE 2
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_KIND_SCROLL 3
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_KIND_CANCEL 4
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_KIND_ENTER 5
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_KIND_LEAVE 6

typedef uint8_t exports_wasi_input_handlers_pointer_handler_pointer_device_t;

#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_POINTER_DEVICE_UNKNOWN 0
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_POINTER_DEVICE_MOUSE 1
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_POINTER_DEVICE_TOUCH 2
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_POINTER_DEVICE_PEN 3

// The button that CHANGED (down/up); none for move/scroll.
typedef uint8_t exports_wasi_input_handlers_pointer_handler_button_t;

#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_BUTTON_NONE 0
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_BUTTON_PRIMARY 1
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_BUTTON_SECONDARY 2
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_BUTTON_MIDDLE 3
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_BUTTON_BACK 4
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_BUTTON_FORWARD 5

// Buttons currently held.
typedef uint8_t exports_wasi_input_handlers_pointer_handler_buttons_t;

#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_BUTTONS_PRIMARY (1 << 0)
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_BUTTONS_SECONDARY (1 << 1)
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_BUTTONS_MIDDLE (1 << 2)
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_BUTTONS_BACK (1 << 3)
#define EXPORTS_WASI_INPUT_HANDLERS_POINTER_HANDLER_BUTTONS_FORWARD (1 << 4)

typedef struct exports_wasi_input_handlers_pointer_handler_pointer_event_t {
  uint32_t   id;
  exports_wasi_input_handlers_pointer_handler_kind_t   kind;
  exports_wasi_input_handlers_pointer_handler_pointer_device_t   device;
  float   x;
  float   y;
  // 0.0..1.0; 0.0 when the device doesn't report pressure.
  float   pressure;
  // Pen tilt in degrees; 0 when unreported.
  float   tilt_x;
  float   tilt_y;
  // Pen barrel rotation in degrees; 0 when unreported.
  float   twist;
  // Scroll deltas (kind == scroll only; surface units, W3C
  // wheel sign: positive = content moves down/right).
  float   scroll_dx;
  float   scroll_dy;
  exports_wasi_input_handlers_pointer_handler_button_t   button;
  exports_wasi_input_handlers_pointer_handler_buttons_t   buttons;
  bool   alt;
  bool   ctrl;
  bool   meta;
  bool   shift;
} exports_wasi_input_handlers_pointer_handler_pointer_event_t;

// Imported Functions from `wandr:ui-shell/metrics@0.1.0`
extern float wandr_ui_shell_metrics_get_density(void);
extern float wandr_ui_shell_metrics_get_font_scale(void);
extern uint32_t wandr_ui_shell_metrics_get_dpi(void);

// Imported Functions from `wandr:ui-shell/lifecycle@0.1.0`
extern wandr_ui_shell_lifecycle_state_t wandr_ui_shell_lifecycle_get_state(void);

// Exported Functions from `wandr:ui-shell/shell-events@0.1.0`
void exports_wandr_ui_shell_shell_events_on_scheduled_callback(uint32_t callback_id);
void exports_wandr_ui_shell_shell_events_on_lifecycle_changed(exports_wandr_ui_shell_shell_events_state_t new_state);

// Exported Functions from `wasi:input-handlers/frame-handler@0.0.2`
void exports_wasi_input_handlers_frame_handler_on_frame(uint64_t nanos);
void exports_wasi_input_handlers_frame_handler_on_resize(uint32_t width, uint32_t height);

// Exported Functions from `wasi:input-handlers/pointer-handler@0.0.2`
void exports_wasi_input_handlers_pointer_handler_on_pointer(exports_wasi_input_handlers_pointer_handler_pointer_event_t *ev);

// Exported Functions from `wandr:ui-shell/frame-pacing@0.1.0`
uint32_t exports_wandr_ui_shell_frame_pacing_next_frame_delay(void);

// Exported Functions from `wandr:ui-shell/startup@0.1.0`
void exports_wandr_ui_shell_startup_on_init(void);

#ifdef __cplusplus
}
#endif
#endif
