#!/usr/bin/env python3
"""
OpenSFSymbols layer-1 generator — the SF-name -> font -> unicode-id chain.

Reads:
  Data/sf-symbols-7.json   — the SF Symbol *name* universe (6984 [name, apple-glyph] pairs).
  Data/fonts/<font>.json   — an open icon FONT's own table: {font, file, license, glyphs:{name:hex}}.
                             (Derived from the set's published webfont; the webfont CSS *is* the
                             name->codepoint map.) One file per usable font.
  Data/overrides.json      — curated  SF-name -> [[font-id, glyph-name], ...]  (hand-verified).

Produces:
  Sources/OpenSFSymbols/Generated.swift — name universe + fonts registry + SF-name -> [IconRef],
                                          where IconRef carries (font, file, glyph, codepoint).
  Data/coverage-report.txt              — mapped(override)/mapped(auto)/MISSING + invalid overrides.

Each SF name resolves to ordered candidates across fonts, so a symbol absent from the preferred
font can be supplied by another. The runtime resolver picks by a configurable font priority.
"""
import json, os, sys, glob
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def load(p): return json.load(open(os.path.join(ROOT, p)))

sf_names = [n for n, _ in load("Data/sf-symbols-7.json")]

fonts = {}   # font-id -> {"file":..., "glyphs":{name:hexstr}}
for fp in sorted(glob.glob(os.path.join(ROOT, "Data/fonts/*.json"))):
    d = json.load(open(fp))
    fonts[d["font"]] = {"file": d["file"], "glyphs": {k: v.lower() for k, v in d["glyphs"].items()}}
if not fonts:
    sys.exit("no Data/fonts/*.json — add an icon font's {font,file,glyphs} table first")

overrides = {k: v for k, v in load("Data/overrides.json").items() if not k.startswith("_")}

# Font preference for auto-matches when several fonts have the same glyph name. Fonts present in
# Data/fonts but absent here are still used (appended). Runtime can override via setPriority.
FONT_PRIORITY = [f for f in ["tabler", "lucide", "remix", "mdi", "fontawesome"] if f in fonts]
FONT_PRIORITY += [f for f in fonts if f not in FONT_PRIORITY]

def glyph_cp(font, glyph):
    return fonts[font]["glyphs"].get(glyph)

def auto_candidates(name):
    """Best-effort: Apple dotted name -> hyphen/flat variants (+ strip style suffixes), matched
    against each font's own glyph names, in font-priority order."""
    variants = {name.replace(".", "-"), name.replace(".", "")}
    for suf in (".fill", ".circle", ".circle.fill", ".square", ".square.fill", ".slash"):
        if name.endswith(suf):
            b = name[:-len(suf)]
            variants.add(b.replace(".", "-")); variants.add(b.replace(".", ""))
    out = []
    for f in FONT_PRIORITY:
        for v in variants:
            if v in fonts[f]["glyphs"]:
                out.append((f, v)); break
    return out

mapping = OrderedDict()          # sf-name -> [(font, glyph, cphex, source)]
n_override = n_auto = n_missing = 0
bad = []

for name in sf_names:
    cands = []
    if name in overrides:
        for font, glyph in overrides[name]:
            cp = glyph_cp(font, glyph) if font in fonts else None
            if cp: cands.append((font, glyph, cp, "override"))
            else:  bad.append((name, font, glyph))
    if cands:
        n_override += 1
    else:
        for font, glyph in auto_candidates(name):
            cands.append((font, glyph, glyph_cp(font, glyph), "auto"))
        if cands: n_auto += 1
        else:     n_missing += 1
    if cands:
        mapping[name] = cands

# ---- emit Generated.swift ---------------------------------------------------------------------
names_blob = "\n".join(sf_names)
fonts_blob = "\n".join(f"{fid}\t{fonts[fid]['file']}" for fid in FONT_PRIORITY)
map_lines = []
for name, cands in mapping.items():
    enc = "|".join(f"{f}:{g}:{cp}:{src}" for f, g, cp, src in cands)
    map_lines.append(f"{name}\t{enc}")
map_blob = "\n".join(map_lines)

def blob(s): return '"""\n' + s.replace("\\", "\\\\") + '\n"""'

swift = f'''// GENERATED by Tools/generate.py — do not edit by hand.
// Regenerate after editing Data/overrides.json or Data/fonts/*.json:  python3 Tools/generate.py
//
// SF-name universe: {len(sf_names)}.  Mapped: {len(mapping)} (override {n_override}, auto {n_auto}).
// Missing: {n_missing}.  Fonts: {", ".join(FONT_PRIORITY)}.

enum OpenSFSymbolsData {{
    static let namesBlob = {blob(names_blob)}

    // "font-id<TAB>font-file"
    static let fontsBlob = {blob(fonts_blob)}

    // "sf-name<TAB>font:glyph:codepoint-hex:source|..."
    static let mappingBlob = {blob(map_blob)}
}}
'''
open(os.path.join(ROOT, "Sources/OpenSFSymbols/Generated.swift"), "w").write(swift)

# ---- coverage report --------------------------------------------------------------------------
missing = [n for n in sf_names if n not in mapping]
r = [f"OpenSFSymbols coverage — SF Symbols 7 ({len(sf_names)} names)  fonts: {', '.join(FONT_PRIORITY)}",
     f"  mapped total : {len(mapping)}",
     f"    override   : {n_override}",
     f"    auto       : {n_auto}",
     f"  MISSING      : {n_missing}"]
if bad:
    r += ["", f"INVALID overrides (glyph not in font) — fix: {len(bad)}"] + [f"    {n} -> {f}/{g}" for n, f, g in bad[:50]]
r += ["", "First 60 MISSING names:"] + [f"    {n}" for n in missing[:60]]
open(os.path.join(ROOT, "Data/coverage-report.txt"), "w").write("\n".join(r) + "\n")
print("\n".join(r[:6]))
if bad: print(f"\nWARNING: {len(bad)} invalid override(s) dropped.", file=sys.stderr)
