// Proof crate: async export generated by wit-bindgen 0.53, compiled + linked +
// run under wasmtime 46 with component-model-async. See README.md.
wit_bindgen::generate!({
    world: "probe",
    async: true,
});

struct Probe;

impl Guest for Probe {
    async fn run(x: u32) -> u32 {
        // trivial async body — the point is that the async export ABI + the
        // async_support runtime drive this to completion.
        x.wrapping_add(1)
    }
}

export!(Probe);
